### ISSUE TITLE
[slyd] Double finish() for non-HtmlResponse types

### ISSUE THREAD

**Issue by okey** [scrapinghub/portia#176]
When loading a non HTML page, e.g. [Haddocks Pipeshop](http://www.haddockspipeshop.com/en/news.xml) from #41, an exception is thrown because [fetch_callback()](https://github.com/scrapinghub/portia/blob/master/slyd/slyd/bot.py#L114) calls `response.finish()` but continues processing the response, so it gets `finish()`ed again later.

Even if #41 was fixed, that link would fail because of this issue.

It seems straightforward to fix but I don't want to file a pull request without knowing what the desired behaviour for various different response types is.
The following might be acceptable, in place of lines 111-114, if nothing else needs supported at the moment?
```python
if not isinstance(response, HtmlResponse) and not isinstance(response, XmlResponse):
    msg = "Non-html response: %s" % response.headers.get(
        'content-type', 'no content type')
    finish_request(request, error=msg)
    return
```

Traceback:
```python-traceback
2015-03-30 16:37:41+1300 [scrapy] Unhandled Error
	Traceback (most recent call last):
	Failure: exceptions.RuntimeError: Request.write called on a request after Request.finish was called.
	
2015-03-30 16:37:41+1300 [scrapy] Spider error processing <GET http://www.haddockspipeshop.com/en/news.xml>
	Traceback (most recent call last):
	  File "/home/okey/work/portia/portia-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/home/okey/work/portia/portia-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/okey/work/portia/portia-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/home/okey/work/portia/portia-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/okey/work/portia/portia-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/okey/work/portia/slyd/slyd/bot.py", line 148, in fetch_callback
	    error="unexpected internal error: %s" % ex)
	  File "/home/okey/work/portia/slyd/slyd/bot.py", line 187, in finish_request
	    trequest.write(jdata)
	  File "/home/okey/work/portia/portia-env/local/lib/python2.7/site-packages/twisted/web/server.py", line 217, in write
	    http.Request.write(self, data)
	  File "/home/okey/work/portia/portia-env/local/lib/python2.7/site-packages/twisted/web/http.py", line 962, in write
	    raise RuntimeError('Request.write called on a request after '
	exceptions.RuntimeError: Request.write called on a request after Request.finish was called.
```

**Comment by ruairif** [comment]
That should be OK. You could also try:

    if not isinstance(response, (HttpResponse, XmlResponse)):

**Comment by pablohoffman** [comment]
typo above, should be `HtmlResponse`
