### ISSUE TITLE
running portialcrawl on vagrant error

### ISSUE THREAD

**Issue by bthibault** [scrapinghub/portia#188]
Fresh vagrant install .

I set up my crawler and to test it ran 

portiacrawl new_project ikea -t csv -o output.csv

I get this error dump no matter what I do. 

Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 4, in <module>
    execute()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 143, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 89, in _run_print_help
    func(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 150, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/crawl.py", line 57, in run
    crawler = self.crawler_process.create_crawler()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 87, in create_crawler
    self.crawlers[name] = Crawler(self.settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 25, in __init__
    self.spiders = spman_cls.from_crawler(self)
  File "/vagrant/slybot/slybot/spidermanager.py", line 30, in from_crawler
    return cls.from_settings(crawler.settings)
  File "/vagrant/slybot/slybot/spidermanager.py", line 36, in from_settings
    return cls(datadir, spider_cls, settings=settings)
  File "/vagrant/slybot/slybot/spidermanager.py", line 22, in __init__
    settings = settings.copy()
AttributeError: 'Settings' object has no attribute 'copy'

**Comment by ruairif** [comment]
Portia was using an outdated version of scrapy. You will need to reprovision vagrant using the latest version of master
