### ISSUE TITLE
 No module named slybot.validation.schema 

### ISSUE THREAD

**Issue by sornalingam** [scrapinghub/portia#197]
Hi All, I have downloaded  SHA : "175b1f5bbec50fda6adda042481bd09c77d12bf0" . And installed all the requirements. 

When i run the following `python C:\Python27\Scripts\twistd.py -n slyd` I got the below error 

`Traceback (most recent call last):
  File "C:\Python27\Scripts\twistd.py", line 14, in <module>
    run()
  File "C:\Python27\lib\site-packages\twisted\scripts\twistd.py", line 27, in ru
n
    app.run(runApp, ServerOptions)
  File "C:\Python27\lib\site-packages\twisted\application\app.py", line 642, in
run
    runApp(config)
  File "C:\Python27\lib\site-packages\twisted\scripts\twistd.py", line 23, in ru
nApp
    _SomeApplicationRunner(config).run()
  File "C:\Python27\lib\site-packages\twisted\application\app.py", line 376, in
run
    self.application = self.createOrGetApplication()
  File "C:\Python27\lib\site-packages\twisted\application\app.py", line 436, in
createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "E:\usr\CDB\portia\slyd\slyd\tap.py", line 88, in makeService
    root = create_root(config)
  File "E:\usr\CDB\portia\slyd\slyd\tap.py", line 45, in create_root
    from .projectspec import create_project_resource
  File "E:\usr\CDB\portia\slyd\slyd\projectspec.py", line 5, in <module>
    from slybot.validation.schema import get_schema_validator
ImportError: No module named slybot.validation.schema`

Thanks,

**Comment by ruairif** [comment]
Follow the install instructions again. You most likely did `pip install slybot` rather than `pip install ./slybot`

**Comment by sornalingam** [comment]
`pip install -e ./slybot`  this solved the problem and thanks
