### ISSUE TITLE
unable to deploy portia project on scrapyd due to 'No module found ..'

### ISSUE THREAD

**Issue by ritesh-gopal** [scrapinghub/portia#209]
I am evaluating portia and run in to an issue deploying to scrapyd.
I have one docker container running portia and another running scrapyd.

When I try to deploy my portia project using

    scrapyd-deploy local -p new_project

from my portia project directory I get the following error message

    Packing version 1433441798
    Deploying to project "new_project" in http://192.168.59.103:6800/addversion.json
    Server response (200):
    {"status": "error", "message": "ImportError: Error loading object 
    'slybot.spidermanager.ZipfileSlybotSpiderManager': No module named slybot.spidermanager"}

My project runs via portiacrawl successfully. I also tried creating a simple scrapy project using the `startproject` and `genspider` commands which deployed successfully on scrapyd

**Scrapyd log**

    2015-06-04 18:28:51+0000 [HTTPChannel,21,172.17.42.1] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1618, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 773, in requestReceived
            self.process()
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 132, in process
            self.render(resrc)
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 167, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/usr/lib/pymodules/python2.7/scrapyd/webservice.py", line 18, in render
            return JsonResource.render(self, txrequest)
          File "/usr/lib/pymodules/python2.7/scrapy/utils/txweb.py", line 10, in render
            r = resource.Resource.render(self, txrequest)
          File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 216, in render
            return m(request)
          File "/usr/lib/pymodules/python2.7/scrapyd/webservice.py", line 66, in render_POST
            spiders = get_spider_list(project)
          File "/usr/lib/pymodules/python2.7/scrapyd/utils.py", line 65, in get_spider_list
            raise RuntimeError(msg.splitlines()[-1])
        exceptions.RuntimeError: ImportError: Error loading object 'slybot.spidermanager.ZipfileSlybotSpiderManager': No module named slybot.spidermanager

    2015-06-04 18:28:51+0000 [HTTPChannel,21,172.17.42.1] 172.17.42.1 - -     [04/Jun/2015:18:28:51 +0000] "POST /addversion.json HTTP/1.1" 200 156 "-" "Python-urllib/2.7"

Any ideas what I am missing ?

**Comment by ruairif** [comment]
Do you have slybot installed in the same environment as scrapyd?

**Comment by ritesh-gopal** [comment]
I installed slybot with 
``` pip install slybot ```

Now I get a different error when deploying my project

```
2015-06-08 20:09:14+0000 [HTTPChannel,0,172.17.42.1] 172.17.42.1 - - [08/Jun/2015:20:09:12 +0000] "POST /addversion.json HTTP/1.1" 200 156 "-" "Python-urllib/2.7"
2015-06-08 20:33:34+0000 [HTTPChannel,1,172.17.42.1] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1618, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 773, in requestReceived
            self.process()
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 132, in process
            self.render(resrc)
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 167, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/usr/lib/pymodules/python2.7/scrapyd/webservice.py", line 18, in render
            return JsonResource.render(self, txrequest)
          File "/usr/lib/pymodules/python2.7/scrapy/utils/txweb.py", line 10, in render
            r = resource.Resource.render(self, txrequest)
          File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 216, in render
            return m(request)
          File "/usr/lib/pymodules/python2.7/scrapyd/webservice.py", line 66, in render_POST
            spiders = get_spider_list(project)
          File "/usr/lib/pymodules/python2.7/scrapyd/utils.py", line 65, in get_spider_list
            raise RuntimeError(msg.splitlines()[-1])
        exceptions.RuntimeError: AttributeError: 'CrawlerSettings' object has no attribute 'copy'
```

**Comment by ruairif** [comment]
Your version of scrapy is out of date please use a version of scrapy >= 0.25

**Comment by ritesh-gopal** [comment]
I am now trying to get this working on the same portia docker container instead of a separate container for scrapyd.
I installed scrapyd on my portia container

Here are the current versions of all modules installed
```
root@6feeefbbac29:/# pip list
You are using pip version 7.0.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
cffi (0.9.2)
characteristic (14.3.0)
cryptography (0.9)
cssselect (0.9.1)
dulwich (0.9.7)
enum34 (1.0.4)
GnuPGInterface (0.3.2)
idna (1.1)
ipaddress (1.0.7)
jsonschema (2.4.0)
loginform (1.0)
lxml (3.4.1)
mysql-connector-python (1.2.3)
numpy (1.9.2)
pip (7.0.1)
pyasn1 (0.1.7)
pyasn1-modules (0.0.5)
pycparser (2.13)
pycurl (7.19.0)
pymongo (3.0.2)
pyOpenSSL (0.15.1)
python-apt (0.8.3ubuntu7.3)
queuelib (1.2.2)
requests (2.5.1)
rfc3987 (1.3.4)
scrapely (0.12.0)
Scrapy (0.25.1, /src/scrapy)
scrapy-mongodb (0.9.0)
scrapyd (1.0.1)
service-identity (14.0.0)
setuptools (15.0)
six (1.9.0)
slybot (0.10)
Twisted (14.0.2)
unattended-upgrades (0.1)
w3lib (1.11.0)
wheel (0.24.0)
zope.interface (4.1.2)
```

The error is slightly different now:
```
Server response (200):
{"status": "error", "message": "AttributeError: 'Settings' object has no attribute 'copy'"}
```

i couldn't find any set of instructions to install `scrapyd` so that portia projects can run on it.

**Comment by ruairif** [comment]
I've reproduced your error message but only by installing the wrong version of scrapy

Scrapy 0.24:
```python
>>> import scrapy
>>> scrapy.__version__
u'0.24.5'
>>> scrapy.settings.Settings.copy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Settings' has no attribute 'copy'
```

Scrapy 0.25:
```python
>>> import scrapy
>>> scrapy.__version__
u'0.25.1'
>>> scrapy.settings.Settings.copy
<unbound method Settings.copy>
```

**Comment by ritesh-gopal** [comment]
I started with the Portia docker container which has Scrapy 0.25.1
In the scrapy shell, the settings.copy works fine

I install scrapyd using
``` 
pip install scrapyd
```
When I try to start up scrapyd, I get the following error: 
```
root@b5ae73afb140:/app/slyd# scrapyd
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/local/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "/usr/local/lib/python2.7/dist-packages/scrapyd/txapp.py", line 3, in <module>
    application = get_application()
  File "/usr/local/lib/python2.7/dist-packages/scrapyd/__init__.py", line 14, in get_application
    return appfunc(config)
  File "/usr/local/lib/python2.7/dist-packages/scrapyd/app.py", line 37, in application
    webservice = TCPServer(http_port, server.Site(Root(config, app)), interface=bind_address)
  File "/usr/local/lib/python2.7/dist-packages/scrapyd/website.py", line 27, in __init__
    servCls = load_object(servClsName)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/scrapyd/webservice.py", line 7, in <module>
    from scrapy.utils.txweb import JsonResource
exceptions.ImportError: No module named txweb

Failed to load application: No module named txweb
```

I check my directory `/usr/local/lib/python2.7/dist-packages/scrapy/utils` and there is no `txweb.py` file

So I installed scrapy using the following
```
pip install -e git://github.com/scrapy/scrapy.git@0.25.1#egg=scrapy
```
This installs in ```src/scrapy/...```
And now I am able to start up scrapyd.
But now the `settings.copy` fails in the scrapy shell

I have come to realize that the portia requirements.txt says to download scrapy from 
`https://github.com/scrapy/scrapy/archive/4b11501eb5bcf12340851a288e9ab89d47793b0f.zip`
which doesn't have txweb.py
When I download the release tag 0.25.1 from github, it has txweb.py but settings.copy doesn't work. 

What is the correct scrapy release zip to use ?

**Comment by ruairif** [comment]
Use the release from Portia and upgrade your scrapyd to the latest version from github.

**Comment by ritesh-gopal** [comment]
Great! That worked.
I used the latest scrapyd version from github with the following command
```
pip install -e git://github.com/scrapy/scrapyd.git#egg=scrapyd
```
