### ISSUE TITLE
Error after renaming Item set (having annotations)

### ISSUE THREAD

**Issue by nestortoledo** [scrapinghub/portia#211]
Error processing POST to http://portia-staging.scrapinghub.com/projects/14338/bot/fetch
with data {"spider":"startuphire","request":{"url":"http://www.startuphire.com/search/?keywords=Mobile&k=fa&location=NY"}}

The server returned error(Internal Server Error)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/app/slyd/slyd/bot.py", line 144, in fetch_callback
    request.project, request.auth_info, params)
  File "/app/slyd/slyd/bot.py", line 182, in create_spider
    self.bot.runner.settings, **kwargs),
  File "/app/slybot/slybot/spider.py", line 44, in __init__
    instance.setup_bot(settings, spec, item_schemas, all_extractors)
  File "/app/slybot/slybot/plugins/scrapely_annotations/annotations.py", line 59, in setup_bot
    schema = items[itemclass_name]
exceptions.KeyError: u'startuphire_items'

**Comment by Youwotma** [comment]
Now the items get assigned an Id that won't change during it's lifetime, so renaming will not cause this problem.
