### ISSUE TITLE
Can't run Portia from Docker

### ISSUE THREAD

**Issue by kmike** [scrapinghub/portia#230]
I've got this error when trying to run Portia built from Docker:

```
Starting nginx: nginx.
/app/slyd/slyd/tap.py:42: ScrapyDeprecationWarning: Module `scrapy.log` has been deprecated, Scrapy now relies on the builtin Python library for logging. Read the updated logging entry in the documentation to learn more.
  from scrapy import log
Traceback (most recent call last):
  File "/usr/local/bin/twistd", line 14, in <module>
    run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 27, in run
    app.run(runApp, ServerOptions)
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 657, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 389, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 449, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/app/slyd/slyd/tap.py", line 88, in makeService
    root = create_root(config, slyd.settings)
  File "/app/slyd/slyd/tap.py", line 46, in create_root
    from .projectspec import create_project_resource
  File "/app/slyd/slyd/projectspec.py", line 5, in <module>
    from slybot.validation.schema import get_schema_validator
ImportError: No module named slybot.validation.schema
```

**Comment by ruairif** [comment]
Can you check what your current version of slybot is. The latest version is 0.11.1

**Comment by kmike** [comment]
I thought the correct version of slybot should be installed by docker. Are there other steps required?

**Comment by Youwotma** [comment]
Yes, It looks like there was an error in the Dockerfile
