### ISSUE TITLE
Try to resolve the "No module named slyd.tap error"?

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#261]
When I start bin/slyd i received the following error in cent-os

slyd]$ bin/slyd
2015-08-27 17:18:29+0530 [-] Log opened.
2015-08-27 17:18:29.318689 [-] Splash version: 1.6
2015-08-27 17:18:29.319315 [-] Qt 4.8.5, PyQt 4.10.1, WebKit 537.21, sip 4.14.6, Twisted 15.2.1, Lua 5.1
2015-08-27 17:18:29.319412 [-] Open files limit: 1024
2015-08-27 17:18:29.319473 [-] Open files limit increased from 1024 to 4096
2015-08-27 17:18:29.534741 [-] Xvfb is started: ['Xvfb', ':2431', '-screen', '0', '1024x768x24']
Xlib: extension "RANDR" missing on display ":2431".
2015-08-27 17:18:29.637987 [-] Traceback (most recent call last):
2015-08-27 17:18:29.638202 [-] File "bin/slyd", line 41, in
2015-08-27 17:18:29.638312 [-] splash.server.main()
2015-08-27 17:18:29.638408 [-] File "/usr/lib/python2.7/site-packages/splash/server.py", line 373, in main
2015-08-27 17:18:29.638572 [-] max_timeout=opts.max_timeout
2015-08-27 17:18:29.638665 [-] File "/usr/lib/python2.7/site-packages/splash/server.py", line 279, in default_splash_server
2015-08-27 17:18:29.638801 [-] max_timeout=max_timeout
2015-08-27 17:18:29.638887 [-] File "bin/slyd", line 15, in make_server
2015-08-27 17:18:29.638981 [-] from slyd.tap import makeService

2015-08-27 17:18:29.639099 [-] ImportError: No module named slyd.tap

How could it resolve

**Comment by ruairif** [comment]
If you look in `portia/slyd/slyd` you should find both an `__init__.py` file and a `tap.py` file. These files should allow `from slyd.tap import makeService` to resolve the correct files to load. If these files are missing you could try adding the `portia/slyd` folder to your python path

**Comment by agramesh** [comment]
Both __init.py__ and tap.py are available in portia/slyd/slyd. but still getting the same error.

**Comment by agramesh** [comment]
Here I am using Cent-os -7, is this portia supported in this OS. If not means how i could resolve it.

**Comment by krelfallahhichem** [comment]
When I start bin/slyd (not in virtualenv) i received the same error.
__init__.py file and  tap.py file not missing in the directory portia/slyd/slyd 
i need help

**Comment by ruairif** [comment]
I've been trying to reproduce this on my debian system but I can't. If you start a python shell in `portia/slyd` does the following work?
```python
from slyd.tap import makeService
```

**Comment by agramesh** [comment]
Yes I started that file from portia/slyd but its produce same error,  if I stop the slyd.tap service in slyd/bin/slyd file its run upto the following...

slyd]$ bin/slyd
2015-09-02 16:53:18+0530 [-] Log opened.
2015-09-02 16:53:18.632846 [-] Splash version: 1.6
2015-09-02 16:53:18.633433 [-] Qt 4.8.5, PyQt 4.10.1, WebKit 537.21, sip 4.14.6, Twisted 15.2.0, Lua 5.1
2015-09-02 16:53:18.633530 [-] Open files limit: 1024
2015-09-02 16:53:18.633589 [-] Open files limit increased from 1024 to 4096
2015-09-02 16:53:18.843980 [-] Xvfb is started: ['Xvfb', ':2507', '-screen', '0', '1024x768x24']
Xlib:  extension "RANDR" missing on display ":2507".

**Comment by ruairif** [comment]
Did you try to import `slyd.tap` in a python console from that folder?

**Comment by agramesh** [comment]
I am not able to import slyd.tap from the path portia/slyd/bin, but i can able to import slyd.tap from the path portia/slyd/.

**Comment by ruairif** [comment]
Can you try adding portia/slyd to your pythonpath?

**Comment by agramesh** [comment]
I have added portia/slyd to python path using export PATH=$PATH:portia/slyd/, but still the same error is found.

**Comment by ruairif** [comment]
`PYTHONPATH=$PYTHONPATH:/PATH/TO/portia/slyd`

**Comment by agramesh** [comment]
yes i tried to add path in many ways but still tap.py file not able to import in bin folder

**Comment by agramesh** [comment]
after adding path for slyd and slybot , then make a small change in slyd/bin/slyd file like this
root = kwargs.get('root', DEFAULT_PORTIA_ROOT)
the portia javascript UI is working

**Comment by malikarzish** [comment]
Even after adding the root path in the file. The Error Still Persists.
