### ISSUE TITLE
Can't build Docker image

### ISSUE THREAD

**Issue by sntran** [scrapinghub/portia#287]
I got this error when building Docker image from Portia repo:

```
Step 6 : RUN pip install -r /requirements-slyd.txt
 ---> Running in 5a85a5d2da58
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting twisted==15.2.1 (from -r /requirements-slyd.txt (line 1))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading Twisted-15.2.1.tar.bz2 (4.6MB)
Collecting service-identity==14.0.0 (from -r /requirements-slyd.txt (line 2))
  Downloading service_identity-14.0.0-py2.py3-none-any.whl
Collecting requests==2.7.0 (from -r /requirements-slyd.txt (line 3))
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
Collecting autobahn==0.10.4 (from -r /requirements-slyd.txt (line 4))
  Downloading autobahn-0.10.4.tar.gz (148kB)
Collecting six==1.5.2 (from -r /requirements-slyd.txt (line 5))
  Downloading six-1.5.2-py2.py3-none-any.whl
Collecting splash==1.6 (from -r /requirements-slyd.txt (line 6))
  Downloading splash-1.6.tar.gz (414kB)
Collecting chardet==2.3.0 (from -r /requirements-slyd.txt (line 7))
  Downloading chardet-2.3.0.tar.gz (164kB)
Collecting monotonic==0.3 (from -r /requirements-slyd.txt (line 8))
  Downloading monotonic-0.3.tar.gz
Collecting dulwich from https://github.com/scrapinghub/dulwich/tarball/420a056#egg=dulwich (from -r /requirements-slyd.txt (line 10))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://github.com/scrapinghub/dulwich/tarball/420a056 (243kB)
Requirement already satisfied (use --upgrade to upgrade): zope.interface>=3.6.0 in /usr/local/lib/python2.7/dist-packages (from twisted==15.2.1->-r /requirements-slyd.txt (line 1))
Collecting pyopenssl>=0.12 (from service-identity==14.0.0->-r /requirements-slyd.txt (line 2))
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB)
Collecting characteristic>=14.0.0 (from service-identity==14.0.0->-r /requirements-slyd.txt (line 2))
  Downloading characteristic-14.3.0-py2.py3-none-any.whl
Collecting pyasn1-modules (from service-identity==14.0.0->-r /requirements-slyd.txt (line 2))
  Downloading pyasn1-modules-0.0.7.tar.gz
Collecting pyasn1 (from service-identity==14.0.0->-r /requirements-slyd.txt (line 2))
  Downloading pyasn1-0.1.8.tar.gz (75kB)
Collecting txaio>=1.0.0 (from autobahn==0.10.4->-r /requirements-slyd.txt (line 4))
  Downloading txaio-2.0.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): qt4reactor in /usr/local/lib/python2.7/dist-packages (from splash==1.6->-r /requirements-slyd.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): psutil in /usr/local/lib/python2.7/dist-packages (from splash==1.6->-r /requirements-slyd.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): adblockparser in /usr/local/lib/python2.7/dist-packages (from splash==1.6->-r /requirements-slyd.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): xvfbwrapper in /usr/local/lib/python2.7/dist-packages (from splash==1.6->-r /requirements-slyd.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): funcparserlib in /usr/local/lib/python2.7/dist-packages (from splash==1.6->-r /requirements-slyd.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): Pillow in /usr/local/lib/python2.7/dist-packages (from splash==1.6->-r /requirements-slyd.txt (line 6))
Collecting mysql-connector-python==1.2.3 (from dulwich->-r /requirements-slyd.txt (line 10))
  Downloading http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-1.2.3.zip (385kB)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from zope.interface>=3.6.0->twisted==15.2.1->-r /requirements-slyd.txt (line 1))
Collecting cryptography>=0.7 (from pyopenssl>=0.12->service-identity==14.0.0->-r /requirements-slyd.txt (line 2))
  Downloading cryptography-1.0.1.tar.gz (332kB)
Collecting idna>=2.0 (from cryptography>=0.7->pyopenssl>=0.12->service-identity==14.0.0->-r /requirements-slyd.txt (line 2))
  Downloading idna-2.0-py2.py3-none-any.whl (61kB)
Collecting enum34 (from cryptography>=0.7->pyopenssl>=0.12->service-identity==14.0.0->-r /requirements-slyd.txt (line 2))
  Downloading enum34-1.0.4.tar.gz
Collecting ipaddress (from cryptography>=0.7->pyopenssl>=0.12->service-identity==14.0.0->-r /requirements-slyd.txt (line 2))
  Downloading ipaddress-1.0.14-py27-none-any.whl
Collecting cffi>=1.1.0 (from cryptography>=0.7->pyopenssl>=0.12->service-identity==14.0.0->-r /requirements-slyd.txt (line 2))
  Downloading cffi-1.2.1.tar.gz (335kB)
Collecting pycparser (from cffi>=1.1.0->cryptography>=0.7->pyopenssl>=0.12->service-identity==14.0.0->-r /requirements-slyd.txt (line 2))
  Downloading pycparser-2.14.tar.gz (223kB)
Building wheels for collected packages: twisted, autobahn, splash, chardet, monotonic, pyasn1-modules, pyasn1, txaio, mysql-connector-python, cryptography, enum34, cffi, pycparser
  Running setup.py bdist_wheel for twisted
  Stored in directory: /root/.cache/pip/wheels/79/16/a4/90178c59ce9fe77b861216d7ce9b69d14fffdbf45c3757e03f
  Running setup.py bdist_wheel for autobahn
  Stored in directory: /root/.cache/pip/wheels/e4/d2/b5/05615fd7ee48e1b019eeb4272992b6c583bd9d080f6f54a34e
  Running setup.py bdist_wheel for splash
  Stored in directory: /root/.cache/pip/wheels/85/c8/0d/9373e861fa8915622736a6ae9bcc4b28a6bf28cedf7cf8ff0b
  Running setup.py bdist_wheel for chardet
  Stored in directory: /root/.cache/pip/wheels/a4/24/b6/124a2516812185506f0573d4abbeb7d08596f53618f8cc960d
  Running setup.py bdist_wheel for monotonic
  Stored in directory: /root/.cache/pip/wheels/0f/cf/72/297c6d473b3f94a80084ed52548c13bea1acf37ca543961393
  Running setup.py bdist_wheel for pyasn1-modules
  Stored in directory: /root/.cache/pip/wheels/82/4f/72/c1306b22a5219e5e46eda7938804c6194748a5fe34198fa557
  Running setup.py bdist_wheel for pyasn1
  Stored in directory: /root/.cache/pip/wheels/c4/c5/95/c73b6aecd3119583f44a299c290a2d94bc3f67ae38728af1ef
  Running setup.py bdist_wheel for txaio
  Stored in directory: /root/.cache/pip/wheels/56/8d/de/8c7e737404c0fc785a6f7e03cf0f1cc50d82313277665eeb33
  Running setup.py bdist_wheel for mysql-connector-python
  Stored in directory: /root/.cache/pip/wheels/11/5e/55/b5c4c76f2decfe7e774f54882457ac1e74da6987e64a1dd325
  Running setup.py bdist_wheel for cryptography
  Stored in directory: /root/.cache/pip/wheels/c9/d5/8d/710fcf0362ebfc2e9dee75f0709c7819bb408f3958f6b1ef4d
  Running setup.py bdist_wheel for enum34
  Stored in directory: /root/.cache/pip/wheels/d1/b2/2c/b51348698bd1921a226cf48d790b282d86fb4bcf9728afd6b3
  Running setup.py bdist_wheel for cffi
  Stored in directory: /root/.cache/pip/wheels/fa/ad/ab/28df6da3b6cf3c510c6dc64f336ef17ef37cd1b0d4d5eff3bc
  Running setup.py bdist_wheel for pycparser
  Stored in directory: /root/.cache/pip/wheels/c7/28/31/bac6d0b118c0bdcbf57f9219afdf2e624379c07efa6c769dbc
Successfully built twisted autobahn splash chardet monotonic pyasn1-modules pyasn1 txaio mysql-connector-python cryptography enum34 cffi pycparser
Installing collected packages: twisted, six, idna, pyasn1, enum34, ipaddress, pycparser, cffi, cryptography, pyopenssl, characteristic, pyasn1-modules, service-identity, requests, txaio, autobahn, splash, chardet, monotonic, mysql-connector-python, dulwich
  Found existing installation: Twisted 15.2.0
    Uninstalling Twisted-15.2.0:
      Successfully uninstalled Twisted-15.2.0
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 299, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 657, in install
    requirement.commit_uninstall()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 739, in commit_uninstall
    self.uninstalled.commit()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 152, in commit
    rmtree(self.save_dir)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 89, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 97, in rmtree_errorhandler
    if os.stat(path).st_mode & stat.S_IREAD:
OSError: [Errno 2] No such file or directory: '/tmp/pip-LzwTa3-uninstall/usr/local/lib/python2.7/dist-packages/twisted/web/domhelpers.pyc'

The command '/bin/sh -c pip install -r /requirements-slyd.txt' returned a non-zero code: 2
```

**Comment by agramesh** [comment]
Upgrade your pip and try to install

**Comment by michiel** [comment]
I had a similar issue and it wasn't the pip version but the cache. I updated my Dockerfile - here's the diff,

    diff --git a/Dockerfile b/Dockerfile
    index 1bfc229..0eadac7 100644
    --- a/Dockerfile
    +++ b/Dockerfile
    @@ -12,9 +12,9 @@ RUN /splash.sh
     
     # Install python stuff.
     ADD slyd/requirements.txt /requirements-slyd.txt
    -RUN pip install -r /requirements-slyd.txt
    +RUN pip install --no-cache-dir -r /requirements-slyd.txt
     ADD slybot/requirements.txt /requirements-slybot.txt
    -RUN pip install -r/requirements-slybot.txt
    +RUN pip install --no-cache-dir -r/requirements-slybot.txt
     
     ENV PYTHONPATH /app/slybot:/app/slyd
     EXPOSE 9001
    @@ -26,7 +26,7 @@ ADD https://easylist-downloads.adblockplus.org/easylist.txt \
     
     RUN ln -sf /app/nginx/nginx.conf /etc/nginx/nginx.conf
     
    -RUN pip install -e /app/slybot /app/slyd
    +RUN pip install --no-cache-dir -e /app/slybot /app/slyd
     
     WORKDIR /app/slyd
     # TODO(dangra): fix handling of nginx service, it won't be restarted in case if crashed.

The original *should* work but doesn't, I'm not sure why. If I find out I'll make a PR for it.
