### ISSUE TITLE
Javascript spiders Deploy in scrapyd

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#290]
While deploying javascript spiders i receive 

   2015-09-28 14:58:01+0530 [HTTPChannel,8,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "C:\Python27\lib\site-packages\twisted\web\http.py", line 1731, i
n allContentReceived
            req.requestReceived(command, path, version)
          File "C:\Python27\lib\site-packages\twisted\web\http.py", line 828, in
 requestReceived
            self.process()
          File "C:\Python27\lib\site-packages\twisted\web\server.py", line 189,
in process
            self.render(resrc)
          File "C:\Python27\lib\site-packages\twisted\web\server.py", line 238,
in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "C:\Python27\lib\site-packages\scrapyd\webservice.py", line 17, i
n render
            return JsonResource.render(self, txrequest)
          File "C:\Python27\lib\site-packages\scrapyd\utils.py", line 19, in ren
der
            r = resource.Resource.render(self, txrequest)
          File "C:\Python27\lib\site-packages\twisted\web\resource.py", line 250
, in render
            return m(request)
          File "C:\Python27\lib\site-packages\scrapyd\webservice.py", line 33, i
n render_POST
            spiders = get_spider_list(project)
          File "C:\Python27\lib\site-packages\scrapyd\utils.py", line 114, in ge
t_spider_list
            raise RuntimeError(msg.splitlines()[-1])
        exceptions.RuntimeError: ImportError: Error loading object 'slybot.spide
rmanager.ZipfileSlybotSpiderManager': No module named linkextractors

is there any other way for deployment in scrapyd.
 for deployment how can it enable the splash itself or we need enable this by manually?

thanks in advance

**Comment by agramesh** [comment]
hi in scrapyd log file no data is extracted while deploying javascript spider, anyone can help me please
here is the sample output


2015-10-29 17:26:40 [scrapy] INFO: Scrapy 1.0.0 started (bot: scrapybot)
2015-10-29 17:26:40 [scrapy] INFO: Optional features available: ssl, http11, boto
2015-10-29 17:26:40 [scrapy] INFO: Overridden settings: {'FEED_URI': 'file:///home/ramesh/items/futureplc/futureplc/1d34e3e07e3411e59f4f000c29363986.jl', 'LOG_FILE': 'logs/futureplc/futureplc/1d34e3e07e3411e59f4f000c29363986.log', 'DOWNLOAD_DELAY': 0.5, 'DUPEFILTER_CLASS': 'scrapyjs.SplashAwareDupeFilter'}
2015-10-29 17:26:40 [scrapy] INFO: Enabled extensions: CloseSpider, FeedExporter, TelnetConsole, LogStats, CoreStats, SpiderState
2015-10-29 17:26:40 [py.warnings] WARNING: /usr/local/lib/python2.7/dist-packages/scrapyjs/middleware.py:8: ScrapyDeprecationWarning: Module `scrapy.log` has been deprecated, Scrapy now relies on the builtin Python library for logging. Read the updated logging entry in the documentation to learn more.
  from scrapy import log

2015-10-29 17:26:41 [py.warnings] WARNING: /usr/local/lib/python2.7/dist-packages/scrapyjs/dupefilter.py:8: ScrapyDeprecationWarning: Module `scrapy.dupefilter` is deprecated, use `scrapy.dupefilters` instead
  from scrapy.dupefilter import RFPDupeFilter

2015-10-29 17:26:41 [py.warnings] WARNING: /usr/local/lib/python2.7/dist-packages/scrapyjs/cache.py:11: ScrapyDeprecationWarning: Module `scrapy.contrib.httpcache` is deprecated, use `scrapy.extensions.httpcache` instead
  from scrapy.contrib.httpcache import FilesystemCacheStorage

2015-10-29 17:26:41 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, SlybotJsMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-10-29 17:26:41 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2015-10-29 17:26:41 [py.warnings] WARNING: /usr/local/lib/python2.7/dist-packages/scrapy/pipelines/__init__.py:21: ScrapyDeprecationWarning: ITEM_PIPELINES defined as a list or a set is deprecated, switch to a dict
  category=ScrapyDeprecationWarning, stacklevel=1)

2015-10-29 17:26:41 [scrapy] INFO: Enabled item pipelines: DupeFilterPipeline
2015-10-29 17:26:41 [scrapy] INFO: Spider opened
2015-10-29 17:26:41 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-10-29 17:26:41 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2015-10-29 17:26:41 [scrapy] DEBUG: Crawled (200) <GET http://www.futureplc.com/yourfuturejob/> (referer: None) ['partial']
2015-10-29 17:26:42 [scrapy] INFO: Closing spider (finished)
2015-10-29 17:26:42 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 229,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 74068,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2015, 10, 29, 11, 56, 42, 113309),
 'log_count/DEBUG': 2,
 'log_count/INFO': 7,
 'log_count/WARNING': 4,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2015, 10, 29, 11, 56, 41, 5878)}
2015-10-29 17:26:42 [scrapy] INFO: Spider closed (finished)

**Comment by ruairif** [comment]
For your issue with deployment it is caused by having an older version or scrapy, please update it to 1.0
For your second issue do you have an instance of splash running and have you included the appropriate settings for using Splash?

**Comment by agramesh** [comment]
my scrapy version is 1.0.0. and i have run the splash instance and included in settings.py file like as
DOWNLOADER_MIDDLEWARES = {
    'slybot.splash.SlybotJsMiddleware': 725
}
DOWNLOAD_HANDLERS = {'s3': None,}
DOWNLOAD_DELAY=0.5
SPLASH_ENABLED = True
SPLASH_ENDPOINT = 'http://localhost:8050/render.html'
SPLASH_WAIT = 2
SPLASH_IMAGES = False

**Comment by ruairif** [comment]
Try using 
```python
SPLASH_URL = 'http://localhost:8050/render.html'
```
Also make sure that your slybot version >= 0.12

**Comment by agramesh** [comment]
yes the slybot version is 0.12.1 
and i add the splash_url,
the splash is enabled in localhost:8050, 
but i cant crawl data by spider. 
how can i find the splash is triggered in spider or not?

**Comment by ruairif** [comment]
If you have `SPLASH_URL` set in your project settings and the `js_enabled` property is true for the spider then it will use JS. if you have some `js_enable` or `js_disable` patterns these may cause the spider to not use splash to render some pages.
You should also check that requests are being made to your splash instance. You can see this by looking at the logs.

**Comment by agramesh** [comment]
JS spider can deployed in scrapyd.
