### ISSUE TITLE
Portia installation: Site instance has no attribute 'setServiceParent'

### ISSUE THREAD

**Issue by belious2015** [scrapinghub/portia#318]
iam trying to install portia on ubuntu 14.04.1 lts os with virtaulenv and pip, i followed the instruction but i'm iam getting this error:
(portia)lyes@Lyes2015:~/portia/portia/slyd$ twistd -n slyd
Unhandled Error
Traceback (most recent call last):
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/application/app.py", line 579, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/python/usage.py", line 262, in parseOptions
    for (cmd, short, parser, doc) in self.subCommands:
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/application/app.py", line 596, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/plugin.py", line 213, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/plugin.py", line 171, in getCache
    provider = pluginModule.load()
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/python/modules.py", line 389, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/plugins/autobahn_endpoints.py", line 32, in <module>
    from twisted.internet.interfaces import IStreamServerEndpointStringParser, \
exceptions.ImportError: cannot import name IStreamClientEndpointStringParser

/home/lyes/portia/portia/slyd/slyd/bot.py:25: ScrapyDeprecationWarning: Module `scrapy.log` has been deprecated, Scrapy now relies on the builtin Python library for logging. Read the updated logging entry in the documentation to learn more.
  from scrapy import signals, log
/home/lyes/portia/portia/slyd/slyd/bot.py:32: ScrapyDeprecationWarning: Module `scrapy.spider` is deprecated, use `scrapy.spiders` instead
  from scrapy.spider import Spider
/home/lyes/portia/portia/slyd/slyd/bot.py:60: ScrapyDeprecationWarning: log.msg has been deprecated, create a python logger and log through it instead
  log.msg("bot initialized", level=log.DEBUG)
Traceback (most recent call last):
  File "/home/lyes/portia/bin/twistd", line 18, in <module>
    run()
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/application/app.py", line 617, in run
    runApp(config)
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/application/app.py", line 348, in run
    self.application = self.createOrGetApplication()
  File "/home/lyes/portia/local/lib/python2.7/site-packages/twisted/application/app.py", line 410, in createOrGetApplication
    ser.setServiceParent(application)
AttributeError: Site instance has no attribute 'setServiceParent'

i have no idea about how to fix that error, some help please
thanks in advance

**Comment by ruairif** [comment]
Hi there. Did you follow the install instructions [here](http://portia.readthedocs.org/en/latest/installation.html)?
You are using `twistd -n slyd` to start portia. This is the old way, the new way to run it is to run `bin/slyd`

**Comment by belious2015** [comment]
i tried to run it with the new way "bin/slyd" and i get other errors.

(portia)lyes@Lyes2015:~/portia/portia/slyd$ bin/slyd 
2015-12-01 20:20:40+0100 [-] Log opened.
2015-12-01 20:20:40.408666 [-] Splash version: 1.8
2015-12-01 20:20:40.409091 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2015-12-01 20:20:40.409199 [-] Qt 4.8.6, PyQt 4.10.4, WebKit 537.21, sip 4.17, Twisted 15.5.0
2015-12-01 20:20:40.409309 [-] Python 2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]
2015-12-01 20:20:40.409446 [-] Open files limit: 1024
2015-12-01 20:20:40.409553 [-] Open files limit increased from 1024 to 4096
2015-12-01 20:20:40.414080 [-] Traceback (most recent call last):
2015-12-01 20:20:40.414352 [-]   File "bin/slyd", line 41, in <module>
2015-12-01 20:20:40.414533 [-]     splash.server.main()
2015-12-01 20:20:40.414681 [-]   File "/home/lyes/portia/local/lib/python2.7/site-packages/splash/server.py", line 344, in main
2015-12-01 20:20:40.414892 [-]     with xvfb.autostart(opts.disable_xvfb) as x:
2015-12-01 20:20:40.415034 [-]   File "/home/lyes/portia/local/lib/python2.7/site-packages/xvfbwrapper.py", line 41, in __enter__
2015-12-01 20:20:40.415192 [-]     self.start()
2015-12-01 20:20:40.415332 [-]   File "/home/lyes/portia/local/lib/python2.7/site-packages/xvfbwrapper.py", line 53, in start
2015-12-01 20:20:40.415492 [-]     stderr=open(os.devnull),
2015-12-01 20:20:40.415634 [-]   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
2015-12-01 20:20:40.415873 [-]     errread, errwrite)
2015-12-01 20:20:40.416015 [-]   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
2015-12-01 20:20:40.416341 [-]     raise child_exception
2015-12-01 20:20:40.416570 [-] OSError: [Errno 2] No such file or directory
(portia)lyes@Lyes2015:~/portia/portia/slyd$

any idea what's going wrong?

**Comment by ruairif** [comment]
It looks like you're missing some library. I'm not sure which. Can you follow the install instructions that I linked above and then try to run it.

**Comment by belious2015** [comment]
i followed the instructions, and now when i try to start slyd i get a new error
(portia)djenane@Lyes2015:~/portia/portia/slyd$ bin/slyd 
2015-12-03 00:02:05+0100 [-] Log opened.
2015-12-03 00:02:05.804089 [-] Splash version: 1.8
2015-12-03 00:02:05.804542 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2015-12-03 00:02:05.804670 [-] Qt 4.8.2, PyQt 4.9.3, WebKit 534.34, sip 4.13.3, Twisted 15.5.0
2015-12-03 00:02:05.804773 [-] Python 2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]
2015-12-03 00:02:05.804897 [-] Open files limit: 1024
2015-12-03 00:02:05.805020 [-] Open files limit increased from 1024 to 4096
2015-12-03 00:02:05.811526 [-] Traceback (most recent call last):
2015-12-03 00:02:05.811784 [-]   File "bin/slyd", line 41, in <module>
2015-12-03 00:02:05.811944 [-]     splash.server.main()
2015-12-03 00:02:05.812092 [-]   File "/home/djenane/portia/local/lib/python2.7/site-packages/splash/server.py", line 344, in main
2015-12-03 00:02:05.812302 [-]     with xvfb.autostart(opts.disable_xvfb) as x:
2015-12-03 00:02:05.812444 [-]   File "/home/djenane/portia/local/lib/python2.7/site-packages/xvfbwrapper.py", line 41, in __enter__
2015-12-03 00:02:05.812594 [-]     self.start()
2015-12-03 00:02:05.812732 [-]   File "/home/djenane/portia/local/lib/python2.7/site-packages/xvfbwrapper.py", line 53, in start
2015-12-03 00:02:05.812884 [-]     stderr=open(os.devnull),
2015-12-03 00:02:05.813030 [-]   File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
2015-12-03 00:02:05.813237 [-]     errread, errwrite)
2015-12-03 00:02:05.813352 [-]   File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
2015-12-03 00:02:05.813641 [-]     raise child_exception
2015-12-03 00:02:05.813798 [-] OSError: [Errno 2] No such file or directory

**Comment by ruairif** [comment]
Can you try installing these packages too and see if it works:
```
apt-get install -qy --no-install-recommends netbase \
                    ca-certificates \
                    xvfb \
                    pkg-config \
                    libqt4-webkit \
                    python-qt4 \
                    libre2 libre2-dev \
                    libicu48 \
                    zlib1g zlib1g-dev \
                    liblua5.2 liblua5.2-dev
```
