### ISSUE TITLE
Error while running portia on docker in ubuntu.

### ISSUE THREAD

**Issue by siddhant-mohan** [scrapinghub/portia#328]
I am getting following error while running portia on docker in ubuntu 14.04.

    2015-12-12 15:34:03.676329 [HTTPChannel,56,127.0.0.1] Unhandled Error
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
        why = self.lineReceived(line)
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1676, in lineReceived
        self.allContentReceived()
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1755, in allContentReceived
        req.requestReceived(command, path, version)
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 823, in requestReceived
        self.process()
    --- <exception caught here> ---
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 189, in process
        self.render(resrc)
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 238, in render
        body = resrc.render(self)
      File "/app/slyd/slyd/splash/ferry.py", line 79, in render
        return WebSocketResource.render(self, request)
      File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/resource.py", line 162, in render
        protocol.makeConnection(transport)
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 487, in     makeConnection
        self.connectionMade()
      File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 88, in     connectionMade
        self._connectionMade()
      File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 2720, in _connectionMade
        WebSocketProtocol._connectionMade(self)
      File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1187, in     _connectionMade
        self.openHandshakeTimeoutCall = txaio.call_later(self.openHandshakeTimeout,     self.onOpenHandshakeTimeout)
      File "/usr/local/lib/python2.7/dist-packages/txaio/_unframework.py", line 43, in _throw_usage_error
        "To use txaio, you must first select a framework "
    exceptions.RuntimeError: To use txaio, you must first select a framework with .use_twisted() or     .use_txaio()

    2015-12-12 15:34:03.684892 [HTTPChannel,56,127.0.0.1] Unhandled Error
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
        return callWithContext({"system": lp}, func, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
        return func(*args,**kw)
    --- <exception caught here> ---
      File "/usr/local/lib/python2.7/dist-packages/qtreactor/qt4base.py", line 100, in _read
        data = w.doRead()
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
        return self._dataReceived(data)
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
        rval = self.protocol.dataReceived(data)
      File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
        why = self.lineReceived(line)
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1676, in lineReceived
        self.allContentReceived()
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1755, in allContentReceived
        req.requestReceived(command, path, version)
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 823, in requestReceived
        self.process()
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 191, in process
        self.processingFailed(failure.Failure())
      File "/app/slyd/slyd/server.py", line 30, in processingFailed
        return WebRequest.processingFailed(self, reason)
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 329, in processingFailed
        self.write(body)
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 217, in write
        http.Request.write(self, data)
      File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1006, in write
        self.transport.writeSequence(l)
    exceptions.AttributeError: 'NoneType' object has no attribute 'writeSequence'

    2015-12-12 15:34:03.685464 [HTTPChannel,56,127.0.0.1] Unhandled Error
    Traceback (most recent call last):
      File "bin/slyd", line 41, in <module>
        splash.server.main()
      File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 386, in main
        reactor.run()
      File "/usr/local/lib/python2.7/dist-packages/qtreactor/qt4base.py", line 282, in run
        self._blockApp.exec_()
      File "/usr/local/lib/python2.7/dist-packages/qtreactor/qt4base.py", line 110, in read
        log.callWithLogger(w, _read)
    --- <exception caught here> ---
      File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
        return callWithContext({"system": lp}, func, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
        return func(*args,**kw)
      File "/usr/local/lib/python2.7/dist-packages/qtreactor/qt4base.py", line 107, in _read
        self.qt_reactor._disconnectSelectable(w, sys.exc_info()[1], False)
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 260, in _disconnectSelectable
        selectable.connectionLost(failure.Failure(why))
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 293, in connectionLost
        protocol.connectionLost(reason)
      File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 98, in     connectionLost
        self._connectionLost(reason)
      File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 2732, in _connectionLost
        WebSocketProtocol._connectionLost(self, reason)
      File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1209, in _connectionLost
        if self.autoPingPendingCall:
    exceptions.AttributeError: 'FerryServerProtocol' object has no attribute 'autoPingPendingCall'

**Comment by ruairif** [comment]
Hi.
Could you post the result of `pip list` so we can see if there are any issues with the versions of libraries you're using.

**Comment by siddhant-mohan** [comment]
adium-theme-ubuntu (0.3.4)
    apt-xapian-index (0.45)
    autobahn (0.10.9)
    autobahntestsuite (0.7.4)
    calendar-indicator (0.3.1)
    cffi (1.3.1)
    characteristic (14.3.0)
    chardet (2.0.1)
    colorama (0.2.5)
    command-not-found (0.3)
    cryptography (1.1.2)
    cssselect (0.9.1)
    debtagshw (0.1)
    defer (1.0.6)
    dirspec (13.10)
    dnspython (1.11.1)
    duplicity (0.6.23)
    enum34 (1.1.1)
    html5lib (0.999)
    httplib2 (0.8)
    idna (2.0)
    ipaddress (1.0.15)
    Jinja2 (2.8)
    klein (15.2.0)
    linecache2 (1.0.0)
    lockfile (0.8)
    lxml (3.3.3)
    MarkupSafe (0.23)
    numpy (1.8.2)
    oauthlib (0.6.3)
    oneconf (0.3.7.14.4.1)
    PAM (0.4.2)
    pexpect (3.1)
    Pillow (2.3.0)
    pip (7.1.2)
    piston-mini-client (0.7.5)
    pyasn1 (0.1.9)
    pyasn1-modules (0.0.8)
    pycparser (2.14)
    pycrypto (2.6.1)
    pycups (1.9.66)
    pycurl (7.19.3)
    pygobject (3.12.0)
    pygpgme (0.3)
    pyOpenSSL (0.15.1)
    pyserial (2.6)
    pysmbc (1.0.14.1)
    python-apt (0.9.3.5ubuntu1)
    python-debian (0.1.21-nmu2ubuntu2)
    pyxdg (0.25)
    queuelib (1.4.2)
    reportlab (3.0)
    requests (2.2.1)
    Scrapy (0.25.0-454-gfa1039f)
    service-identity (14.0.0)
    sessioninstaller (0.0.0)
    setuptools (18.8)
    six (1.10.0)
    software-center-aptd-plugins (0.0.0)
    ssh-import-id (3.21)
    system-service (0.1.6)
    traceback2 (1.4.0)
    Twisted (15.5.0)
    Twisted-Conch (13.2.0)
    Twisted-Core (13.2.0)
    Twisted-Lore (13.2.0)
    Twisted-Mail (13.2.0)
    Twisted-Names (13.2.0)
    Twisted-News (13.2.0)
    Twisted-Runner (13.2.0)
    Twisted-Web (13.2.0)
    Twisted-Words (13.2.0)
    txaio (2.1.0)
    ujson (1.34)
    unittest2 (1.1.0)
    unity-lens-photos (1.0)
    urllib3 (1.7.1)
    virtualenv (1.11.4)
    w3lib (1.13.0)
    Werkzeug (0.11.2)
    wheel (0.24.0)
    wsaccel (0.6.2)
    xdiagnose (3.6.3build2)
    zope.interface (4.1.3)
    The directory '/home/siddhant/.cache/pip/http' or its parent directory is not owned by the current user     and the cache has been disabled. Please check the permissions and owner of that directory. If     executing pip with sudo, you may want sudo's -H flag.
    /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90:     InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from     configuring SSL appropriately and may cause certain SSL connections to fail. For more information,     see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
      InsecurePlatformWarning

**Comment by ruairif** [comment]
Could you try downgrading autobahn to `0.10.4`

**Comment by siddhant-mohan** [comment]
Nope, error is still the same.

**Comment by ruairif** [comment]
What about downgrading twisted to `15.2.1`

**Comment by siddhant-mohan** [comment]
its still the same.

**Comment by ruairif** [comment]
Try following the install instructions again but this time run the install inside a virtualenv

**Comment by Youwotma** [comment]
@siddhant-mohan It's fixed now in the develop branch

**Comment by siddhant-mohan** [comment]
@Youwotma yeah its working now. great.
