### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, int found

### ISSUE THREAD

**Issue by bigzie** [scrapinghub/portia#342]
Hi guys,
Hope I'm doing this Issue correct.

I did everything according to this guide http://portia.readthedocs.org/en/latest/installation.html#running-portia-locally
to configure portia to run locally

After following this issue https://github.com/scrapinghub/portia/issues/261 which fixed my first issue.

Now I'm having trouble with the following issue.

>linux@server3:~/dev/portia/slyd$ bin/slyd
2016-01-19 21:18:43+0100 [-] Log opened.
2016-01-19 21:18:43.989076 [-] Splash version: 1.8
2016-01-19 21:18:43.989539 [-] Qt 4.8.6, PyQt 4.10.4, WebKit 537.21, sip 4.15.5, Twisted 15.2.1, Lua 5.2
2016-01-19 21:18:43.989602 [-] Python 2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]
2016-01-19 21:18:43.989674 [-] Open files limit: 1024
2016-01-19 21:18:43.989752 [-] Open files limit increased from 1024 to 4096
2016-01-19 21:18:44.192279 [-] Xvfb is started: ['Xvfb', ':1705', '-screen', '0', '1024x768x24']
Xlib:  extension "RANDR" missing on display ":1705".
2016-01-19 21:18:44.445968 [-] /home/linux/dev/portia/slyd/slyd/bot.py:25: scrapy.exceptions.ScrapyDeprecationWarning: Module `scrapy.log` has been deprecated, Scrapy now relies on the builtin Python library for logging. Read the updated logging entry in the documentation to learn more.
2016-01-19 21:18:44.448727 [-] /home/linux/dev/portia/slyd/slyd/bot.py:32: scrapy.exceptions.ScrapyDeprecationWarning: Module `scrapy.spider` is deprecated, use `scrapy.spiders` instead
2016-01-19 21:18:44.474977 [-] Traceback (most recent call last):
2016-01-19 21:18:44.475171 [-]   File "bin/slyd", line 41, in <module>
2016-01-19 21:18:44.475299 [-]     splash.server.main()
2016-01-19 21:18:44.475404 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 372, in main
2016-01-19 21:18:44.475558 [-]     max_timeout=opts.max_timeout
2016-01-19 21:18:44.475652 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 278, in default_splash_server
2016-01-19 21:18:44.475803 [-]     max_timeout=max_timeout
2016-01-19 21:18:44.475888 [-]   File "bin/slyd", line 20, in make_server
2016-01-19 21:18:44.475985 [-]     'docroot': root}))
2016-01-19 21:18:44.476061 [-]   File "/home/linux/dev/portia/slyd/slyd/tap.py", line 105, in makeService
2016-01-19 21:18:44.476169 [-]     root = create_root(config, settings_module)
2016-01-19 21:18:44.476243 [-]   File "/home/linux/dev/portia/slyd/slyd/tap.py", line 57, in create_root
2016-01-19 21:18:44.476327 [-]     for file_name in listdir(config['docroot']):
2016-01-19 21:18:44.476408 [-] TypeError: coercing to Unicode: need string or buffer, int found

<>

Where did I go wrong. Im running it localy

**Comment by bigzie** [comment]
recommendation,
Use Vagrant http://portia.readthedocs.org/en/latest/installation.html#vagrant-recommended
its easier :)
