### ISSUE TITLE
buf must be a byte string

### ISSUE THREAD

**Issue by flip111** [scrapinghub/portia#351]
```
(portia)ubuntu@pi●~/portia/portia [master●] 
» pip install -r slyd/requirements.txt                                                                                      [16:14:19]
Downloading/unpacking http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-1.2.3.zip (from -r slyd/requirements.txt (line 12))
  Downloading mysql-connector-python-1.2.3.zip (385kB): 385kB downloaded
  Running setup.py (path:/tmp/pip-kfCHbN-build/setup.py) egg_info for package from http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-1.2.3.zip

    warning: no files found matching '*.py' under directory 'python23/tests23'
    warning: no files found matching 'pylint*.rc' under directory 'tests'
  Requirement already satisfied (use --upgrade to upgrade): mysql-connector-python==1.2.3 from http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-1.2.3.zip in /home/ubuntu/portia/lib/python2.7/site-packages (from -r slyd/requirements.txt (line 12))
Downloading/unpacking https://github.com/scrapinghub/splash/archive/3acde4ef0d389e5067d51dcc9b4ac6d260658757.tar.gz (from -r slyd/requirements.txt (line 17))
  Downloading 3acde4ef0d389e5067d51dcc9b4ac6d260658757.tar.gz (231kB): 231kB downloaded
  Running setup.py (path:/tmp/pip-6t88Nl-build/setup.py) egg_info for package from https://github.com/scrapinghub/splash/archive/3acde4ef0d389e5067d51dcc9b4ac6d260658757.tar.gz

    warning: no files found matching '*.rst' under directory 'splash/lua_modules'
    warning: no files found matching '*.txt' under directory 'splash/lua_modules'
    warning: no files found matching '*.js' under directory 'splash/vendor/harviewer/webapp'
    warning: no files found matching '*.html' under directory 'splash/vendor/harviewer/webapp'
    warning: no files found matching '*.css' under directory 'splash/vendor/harviewer/webapp'
    warning: no files found matching '*.gif' under directory 'splash/vendor/harviewer/webapp'
    warning: no files found matching '*.png' under directory 'splash/vendor/harviewer/webapp'
    warning: no files found matching '*.swf' under directory 'splash/vendor/harviewer/webapp'
    warning: no files found matching '*.html' under directory 'splash/vendor/harviewer/webapp'
Requirement already satisfied (use --upgrade to upgrade): twisted==15.2.1 in /home/ubuntu/portia/lib/python2.7/site-packages (from -r slyd/requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): service-identity==14.0.0 in /home/ubuntu/portia/lib/python2.7/site-packages (from -r slyd/requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /home/ubuntu/portia/lib/python2.7/site-packages (from -r slyd/requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): autobahn==0.10.4 in /home/ubuntu/portia/lib/python2.7/site-packages (from -r slyd/requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): six==1.5.2 in /home/ubuntu/portia/lib/python2.7/site-packages (from -r slyd/requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): chardet==2.3.0 in /home/ubuntu/portia/lib/python2.7/site-packages (from -r slyd/requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): monotonic==0.3 in /home/ubuntu/portia/lib/python2.7/site-packages (from -r slyd/requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): ndg-httpsclient==0.4.0 in /home/ubuntu/portia/lib/python2.7/site-packages (from -r slyd/requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): dulwich from https://github.com/scrapinghub/dulwich/tarball/420a056 in /home/ubuntu/portia/lib/python2.7/site-packages (from -r slyd/requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): qt4reactor in /home/ubuntu/portia/lib/python2.7/site-packages (from splash==1.8->-r slyd/requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): psutil in /home/ubuntu/portia/lib/python2.7/site-packages (from splash==1.8->-r slyd/requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): adblockparser in /home/ubuntu/portia/lib/python2.7/site-packages (from splash==1.8->-r slyd/requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): xvfbwrapper in /home/ubuntu/portia/lib/python2.7/site-packages (from splash==1.8->-r slyd/requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): funcparserlib in /home/ubuntu/portia/lib/python2.7/site-packages (from splash==1.8->-r slyd/requirements.txt (line 17))
Downloading/unpacking Pillow (from splash==1.8->-r slyd/requirements.txt (line 17))
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/index.py", line 194, in find_requirement
    page = self._get_page(main_index_url, req)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/index.py", line 670, in get_page
    resp = session.get(url, headers={"Accept": "text/html"})
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 395, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 506, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 168, in resolve_redirects
    allow_redirects=False,
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 480, in urlopen
    body=body, headers=headers)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 285, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 811, in send
    self.sock.sendall(data)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 323, in sendall
    return self.connection.sendall(data)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 969, in sendall
    raise TypeError("buf must be a byte string")
TypeError: buf must be a byte string

Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

**Comment by ruairif** [comment]
What version of `pyOpenSSL` have you got? (`pip list | grep -i pyOpenSSL`)
If it is less that 0.15 update it and try again.

**Comment by flip111** [comment]
it's 0.14 .. how come? i used virtualenv and just installed the dependencies...

**Comment by ruairif** [comment]
I'm not sure. When I ran the install it installed the 0.15.2 version. If you run `pip install --upgrade pyOpenSSL` does it upgrade?

**Comment by flip111** [comment]
When i try that command i get the same error again
```
» pip install --upgrade pyOpenSSL
Cleaning up...
Exception:
---- lots of stuff here ----
TypeError: buf must be a byte string
```
