### ISSUE TITLE
portiacrawl command not found

### ISSUE THREAD

**Issue by Gwai2Lo2** [scrapinghub/portia#369]
I'm finally ready to crawl but when executing 

`portiacrawl /Users/<user>/Software/90\ Web\ Scraping/portia/slyd/slyd/data/projects/<project_name>`

to get all spiders listed for the project, I always receive the following error message

`-bash: portiacrawl: command not found`

I'm using

- Mac
- vagrant
- virtual box

I have also observed that in the documentation the path for the projects is

`/slyd/data/projects/`

instead of (my system)

`/slyd/slyd/data/projects/`

The same problem was described here, but it doesn't help:
#30

**Comment by ruairif** [comment]
The `portiacrawl` program isn't added to your system path. If you want to run your spider change directory to `portia/slybot/bin` and run `portiacrawl` from there

**Comment by Gwai2Lo2** [comment]
I have navigated in the terminal to `portia/slybot/bin` and ran `portiacrawl` again, but I till receive the same error.

`-bash: portiacrawl: command not found`

When I doubleclick on the portiacrawl file in `portia/slybot/bin`from the finder, it opens in the terminal and gives me the description, which looks everything alright.

**Comment by ruairif** [comment]
To run it in the terminal you ned to use `./portiacrawl` from the terminal. If you want to be able to run it as just `portiacrawl` from any directory add the directory that `portiacrawl` is in [to your path](http://coolestguidesontheplanet.com/add-shell-path-osx/)

**Comment by Gwai2Lo2** [comment]
thanks, I'm one step further

Do I have to be in a specific directory in the terminal or does the directory not matter?

now, I can execute the portiacrawl command:

`/Users/<user>/Software/90\ Web\ Scraping/portia/slybot/bin/portiacrawl /Users/<user>/Software/90\ Web\ Scraping/portia/slyd/slyd/data/projects/wg_gesucht wg-gesucht.de
`

but it gives out the following error message:

`Traceback (most recent call last):
  File "/Users/<user>/Software/90 Web Scraping/portia/slybot/bin/portiacrawl", line 65, in <module>
    main()
  File "/Users/<user>/Software/90 Web Scraping/portia/slybot/bin/portiacrawl", line 63, in main
    subprocess.call(command_spec)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

What I'm also asking myself is how does the terminal determine between the spaces in the path and the spaces between `portiacrawl PROJECT_PATH SPIDER_NAME` ?

**Comment by ruairif** [comment]
You have `\ ` in the path and ` ` between the arguments.
if you run `cd /Users/<user>/Software/90\ Web\ Scraping/portia/` you can shorten the run command to:
`slybot/bin/portiacrawl slyd/slyd/data/projects/wg_gesucht wg-gesucht.de`

I think the error is because you don't have scrapy installed. Can you try running those commands from inside the vagrant vm? You can use `vagrant ssh` to access the vagrant VM, then `cd /vagrant` and then try to run the command that I gave you above. You can also look into `scrapyd` for running your spiders.

**Comment by Gwai2Lo2** [comment]
I received the following:

```
 /usr/local/lib/python2.7/dist-packages/scrapy/crawler.py:115: ScrapyDeprecationWarning: SPIDER_MANAGER_CLASS option is deprecated. Please use SPIDER_LOADER_CLASS.
  self.spider_loader = _get_spider_loader(settings)
2016-02-08 14:00:25 [scrapy] INFO: Scrapy 1.0.0 started (bot: scrapybot)
2016-02-08 14:00:25 [scrapy] INFO: Optional features available: ssl, http11
2016-02-08 14:00:25 [scrapy] INFO: Overridden settings: {'DUPEFILTER_CLASS': 'scrapyjs.SplashAwareDupeFilter'}
2016-02-08 14:00:25 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2016-02-08 14:00:25 [py.warnings] WARNING: /usr/local/lib/python2.7/dist-packages/scrapyjs/middleware.py:8: ScrapyDeprecationWarning: Module `scrapy.log` has been deprecated, Scrapy now relies on the builtin Python library for logging. Read the updated logging entry in the documentation to learn more.
  from scrapy import log

2016-02-08 14:00:25 [py.warnings] WARNING: /usr/local/lib/python2.7/dist-packages/scrapyjs/dupefilter.py:8: ScrapyDeprecationWarning: Module `scrapy.dupefilter` is deprecated, use `scrapy.dupefilters` instead
  from scrapy.dupefilter import RFPDupeFilter

2016-02-08 14:00:25 [py.warnings] WARNING: /usr/local/lib/python2.7/dist-packages/scrapyjs/cache.py:11: ScrapyDeprecationWarning: Module `scrapy.contrib.httpcache` is deprecated, use `scrapy.extensions.httpcache` instead
  from scrapy.contrib.httpcache import FilesystemCacheStorage

2016-02-08 14:00:25 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, PageActionsMiddleware, CookiesMiddleware, SlybotJsMiddleware, ChunkedTransferMiddleware, DownloaderStats
2016-02-08 14:00:25 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2016-02-08 14:00:25 [scrapy] INFO: Enabled item pipelines: DupeFilterPipeline
2016-02-08 14:00:25 [scrapy] INFO: Spider opened
2016-02-08 14:00:25 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-02-08 14:00:25 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2016-02-08 14:00:27 [scrapy] DEBUG: Crawled (200) <GET http://www.wg-gesucht.de/> (referer: None) ['partial']
```



And I can't remember that I installed scrapy, I thought that it would be automatically installed with portia?
In which folder should I install it?

**Comment by Gwai2Lo2** [comment]
I changed the settings in the crawler sections and now it is running continuously albeit not where I exactly want to retrieve the data, but this I can figure out later.

Thanks a bunch! Without you I would be never able to get this running!

**Comment by ruairif** [comment]
When you are running the spider you can use `-o output.json` to output the data as json. Find out more [here](http://doc.scrapy.org/en/latest/topics/feed-exports.html)
