### ISSUE TITLE
Error starting up Slyd / nginx 502 Bad Gateway error

### ISSUE THREAD

**Issue by ShunLuk** [scrapinghub/portia#442]
Hey, I'm trying to run Portia through Vagrant and I've tried to make sure all the dependencies are met completely but I keep getting a 502 Bad Gateway error when I try to access localhost:9001. turns out, when I SSH and try to run Slyd, I get this:

```
2016-03-30 07:38:49+0000 [-] Log opened.
2016-03-30 07:38:49.224754 [-] Splash version: 2.0.3
2016-03-30 07:38:49.225470 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.0.0, Lua 5.2
2016-03-30 07:38:49.225704 [-] Python 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
2016-03-30 07:38:49.225904 [-] Open files limit: 1024
2016-03-30 07:38:49.226132 [-] Open files limit increased from 1024 to 4096
2016-03-30 07:38:49.330372 [-] Xvfb is started: ['Xvfb', ':1', '-screen', '0', '1024x768x24']
2016-03-30 07:38:50.052222 [-] Traceback (most recent call last):
2016-03-30 07:38:50.052652 [-]   File "/usr/local/bin/slyd", line 10, in <module>
2016-03-30 07:38:50.052916 [-]     execfile(__file__)
2016-03-30 07:38:50.053172 [-]   File "/vagrant/slyd/bin/slyd", line 28, in <module>
2016-03-30 07:38:50.053824 [-]     splash.server.main(server_factory=make_server, argv=[])
2016-03-30 07:38:50.054162 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 361, in main
2016-03-30 07:38:50.054446 [-]     server_factory=server_factory,
2016-03-30 07:38:50.054704 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 281, in default_splash_server
2016-03-30 07:38:50.054985 [-]     max_timeout=max_timeout
2016-03-30 07:38:50.055240 [-]   File "/vagrant/slyd/bin/slyd", line 25, in make_server
2016-03-30 07:38:50.055979 [-]     'docroot': opts.root}))
2016-03-30 07:38:50.056367 [-]   File "/vagrant/slyd/slyd/tap.py", line 103, in makeService
2016-03-30 07:38:50.057115 [-]     root = create_root(config, settings_module)
2016-03-30 07:38:50.057500 [-]   File "/vagrant/slyd/slyd/tap.py", line 55, in create_root
2016-03-30 07:38:50.058225 [-]     for file_name in listdir(config['docroot']):
2016-03-30 07:38:50.058610 [-] OSError: [Errno 2] No such file or directory: './dist'
```
As I understand it, the /dist directory can't be found, but when I look into the directory itself it's right there. I've looked around in past issues and #441 and #320 seem to also be about not being able to access localhost:9001, however they simply got a connection reset error. Has anyone else encountered this issue before?

**Comment by ShunLuk** [comment]
I've found a workaround by changing the value of DEFAULT_PORTIA_ROOT in /slyd/bin/slyd to an absolute path.

**Comment by Elliott19** [comment]
Thanks, localhost:9001 works for me when replacing DEFAULT_PORTIA_ROOT = './dist' with DEFAULT_PORTIA_ROOT = '/vagrant/slyd/dist' in the slyd file

**Comment by devNo0b** [comment]
Can we close this issue please ?
