### ISSUE TITLE
Portiacrawl Export CSV with Docker

### ISSUE THREAD

**Issue by cuervocomando666** [scrapinghub/portia#446]
Hi

I have a instance of portia working with docker on Debian 8 with Python 2.7.9. All function work well on web, but when I use portiacrawl to export result in csv format I have a problem.
 I don't meet path right to run portiacrawl, I use <find -name "*portiacrawl*"> command for found  possible path of portiacrawl.

I'm doing the following:

**First path of portiacrawl:**
./var/lib/docker/aufs/diff/04d79e05faf35b44626d97db4b98489082ca91e8b541329a8b28d8f407570cd8/app/slybot/bin/portiacrawl  /var/lib/docker/volumes/crowdb3/_data/projects/new_project corporativo.abc.com  -t  csv  -o  test.csv

**Error:**
Traceback (most recent call last):
  File "./var/lib/docker/aufs/diff/04d79e05faf35b44626d97db4b98489082ca91e8b541329a8b28d8f407570cd8/app/slybot/bin/portiacrawl", line 65, in <module>
    main()
  File "./var/lib/docker/aufs/diff/04d79e05faf35b44626d97db4b98489082ca91e8b541329a8b28d8f407570cd8/app/slybot/bin/portiacrawl", line 63, in main
    subprocess.call(command_spec)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Second path of portiacrawl:**
./var/lib/docker/aufs/diff/6105d30acdddfa572d63fd15cdb3a4e94f0828d041a380bb6cd67268b2330795/usr/local/bin/portiacrawl /var/lib/docker/volumes/crowdb3/_data/projects/new_project corporativo.tia.com.ec -t csv -o prueba.csv

**Error:**
Traceback (most recent call last):
  File "./var/lib/docker/aufs/diff/6105d30acdddfa572d63fd15cdb3a4e94f0828d041a380bb6cd67268b2330795/usr/local/bin/portiacrawl", line 5, in <module>
    from pkg_resources import require
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 3138, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 661, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 962, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'slybot==0.13.0b16' distribution was not found and is required by the application

Any contribution will help

thanks.

**Comment by ruairif** [comment]
If you are running it through docker make sure that the directory that you're extracting to has write permissions. If you are running it locally make sure that you have slybot installed
