### ISSUE TITLE
Start slyd issue - twistd -n slyd

### ISSUE THREAD

**Issue by ovntatar** [scrapinghub/portia#483]
after successfully installation:

```
$ pip install virtualenv
$ virtualenv portia
$ source portia/bin/activate
$ cd portia
$ git clone https://github.com/scrapinghub/portia
$ cd portia/slyd
$ pip install twisted
$ pip install Scrapy 
$ pip install -r requirements.txt
$ twistd -n slyd
```

get the following error message 

```
twistd -n slyd
/home/ubuntu/portia/portia/slyd/slyd/bot.py:25: ScrapyDeprecationWarning: Module `scrapy.log` has been deprecated, Scrapy now relies on the builtin Python library for logging. Read the updated logging entry in the documentation to learn more.
  from scrapy import signals, log
/home/ubuntu/portia/portia/slyd/slyd/bot.py:32: ScrapyDeprecationWarning: Module `scrapy.spider` is deprecated, use `scrapy.spiders` instead
  from scrapy.spider import Spider
Traceback (most recent call last):
  File "/home/ubuntu/portia/bin/twistd", line 18, in <module>
    run()
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/twisted/application/app.py", line 643, in run
    runApp(config)
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/twisted/application/app.py", line 374, in run
    self.application = self.createOrGetApplication()
  File "/home/ubuntu/portia/local/lib/python2.7/site-packages/twisted/application/app.py", line 434, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/home/ubuntu/portia/portia/slyd/slyd/tap.py", line 107, in makeService
    root = create_root(config, settings_module)
  File "/home/ubuntu/portia/portia/slyd/slyd/tap.py", line 48, in create_root
    from slyd.projects import create_projects_manager_resource
  File "/home/ubuntu/portia/portia/slyd/slyd/projects.py", line 11, in <module>
    from .utils.download import FileSystemProjectArchiver
  File "/home/ubuntu/portia/portia/slyd/slyd/utils/download.py", line 12, in <module>
    from slybot.plugins.scrapely_annotations.builder import Annotations
ImportError: No module named builder
```

any ideas to solve it

**Comment by ruairif** [comment]
Can you try installing slybot from the repo rather than requirements?

```
cd portia/slybot
pip install -e ./
```

**Comment by zhaobingkun** [comment]
I get same error!
Traceback (most recent call last):
  File "/usr/local/bin/twistd", line 14, in <module>
    run()
  File "/usr/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 617, in run
    runApp(config)
  File "/usr/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 348, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 408, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/soft/portia/slyd/slyd/tap.py", line 107, in makeService
    root = create_root(config, settings_module)
  File "/soft/portia/slyd/slyd/tap.py", line 48, in create_root
    from slyd.projects import create_projects_manager_resource
  File "/soft/portia/slyd/slyd/projects.py", line 11, in <module>
    from .utils.download import FileSystemProjectArchiver
  File "/soft/portia/slyd/slyd/utils/download.py", line 12, in <module>
    from slybot.plugins.scrapely_annotations.builder import Annotations
ImportError: No module named builder

**Comment by KaDaniil** [comment]
I have the same error.. Does anyone has a solution?

**Comment by ruairif** [comment]
Update your version of slybot to 0.13.0b32
