### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0

### ISSUE THREAD

**Issue by artyomboyko** [scrapinghub/portia#490]
Using latest version.
Trying this url to create new spider - http://www.foxtrot.com.ua/

```
2016-06-03 20:16:44.367206 [-] "176.36.220.234" - - [03/Jun/2016:20:16:42 +0000] "GET /proxy?url=http%3A%2F%2Fwww.foxtrot.com.ua%2FContent%2Fthemes%2Fbase%2Fall.css&tabid=140482191453968&referer=www.foxtrot.com.ua HTTP/1.1" 200 515 "http://127.0.0.1:9001/static/empty-frame.html?30e6-2486-dc14" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/splash/browser_tab.py", line 977, in _on_request_finished
    callback()
  File "/usr/local/lib/python2.7/dist-packages/splash/browser_tab.py", line 1000, in _return_reply
    callback(reply)
  File "/home/portia/slyd/slyd/splash/proxy.py", line 107, in end_response
    content = process_css(content, tabid, original_url)
  File "/home/portia/slyd/slyd/splash/css_utils.py", line 53, in process_css
    css_source = CSS_URL.sub(_absolutize_css_url, css_source)
  File "/home/portia/slyd/slyd/splash/css_utils.py", line 50, in _absolutize_css_url
    base_uri).replace('"', '%22'))
  File "/home/portia/slyd/slyd/splash/css_utils.py", line 17, in wrap_url
    url = urljoin(base, url).encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 41: ordinal not in range(128)
Aborted
```

**Comment by artyomboyko** [comment]
Anyone ?

**Comment by dongchirua** [comment]
There is a case: http://www.centarahotelsresorts.com/exclusive-room-offers/

**Comment by icamys** [comment]
Got the same issue with current latest version.

**Comment by michelecafagna26** [comment]
Same issue latest version using docker
