### ISSUE TITLE
I get error text centos6.5 python2.7.9 scrapy1.1

### ISSUE THREAD

**Issue by zhaobingkun** [scrapinghub/portia#544]
Traceback (most recent call last):
  File "/usr/local/bin/twistd", line 14, in <module>
    run()
  File "/usr/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 617, in run
    runApp(config)
  File "/usr/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 348, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 408, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/soft/portia/slyd/slyd/tap.py", line 107, in makeService
    root = create_root(config, settings_module)
  File "/soft/portia/slyd/slyd/tap.py", line 48, in create_root
    from slyd.projects import create_projects_manager_resource
  File "/soft/portia/slyd/slyd/projects.py", line 11, in <module>
    from .utils.download import FileSystemProjectArchiver
  File "/soft/portia/slyd/slyd/utils/download.py", line 12, in <module>
    from slybot.plugins.scrapely_annotations.builder import Annotations
ImportError: No module named builder

**Comment by agramesh** [comment]
Install the builder using
pip install builder

**Comment by ruairif** [comment]
@zhaobingkun You are using an outdated version of slybot. Can you try updating to the latest version
