### ISSUE TITLE
Portia 2.0:  On starting slyd "no module named portia_server.settings"

### ISSUE THREAD

**Issue by wildgarden** [scrapinghub/portia#667]
fresh checkout of branch `nui-develop` @ https://github.com/scrapinghub/portia/commit/9693bc16d87ba5f9c066c8e857223472eedac8de

- vagrant up finished, but slyd wasn't running
- ssh into vagrant
- starting slyd results in given output (same result with running provish.sh manually, too):
```
vagrant@portia:/vagrant$ slyd
2017-01-04 14:07:25+0000 [-] Log opened.
2017-01-04 14:07:25.624391 [-] Splash version: 2.3
2017-01-04 14:07:25.628592 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-01-04 14:07:25.628963 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-01-04 14:07:25.629282 [-] Python 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
2017-01-04 14:07:25.629683 [-] Open files limit: 1024
2017-01-04 14:07:25.630017 [-] Open files limit increased from 1024 to 4096
2017-01-04 14:07:25.737957 [-] Xvfb is started: ['Xvfb', ':131618653', '-screen', '0', '1024x768x24']
2017-01-04 14:07:26.379123 [-] Traceback (most recent call last):
2017-01-04 14:07:26.379547 [-]   File "/usr/local/bin/slyd", line 10, in <module>
2017-01-04 14:07:26.379922 [-]     execfile(__file__)
2017-01-04 14:07:26.380326 [-]   File "/vagrant/slyd/bin/slyd", line 28, in <module>
2017-01-04 14:07:26.382002 [-]     splash.server.main(server_factory=make_server, argv=[])
2017-01-04 14:07:26.382417 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 372, in main
2017-01-04 14:07:26.382756 [-]     server_factory=server_factory,
2017-01-04 14:07:26.383101 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 291, in default_splash_server
2017-01-04 14:07:26.383455 [-]     argument_cache_max_entries=argument_cache_max_entries,
2017-01-04 14:07:26.383790 [-]   File "/vagrant/slyd/bin/slyd", line 25, in make_server
2017-01-04 14:07:26.384949 [-]     'docroot': opts.root}))
2017-01-04 14:07:26.385285 [-]   File "/vagrant/slyd/slyd/tap.py", line 88, in makeService
2017-01-04 14:07:26.386445 [-]     root = create_root(config, settings_module)
2017-01-04 14:07:26.386891 [-]   File "/vagrant/slyd/slyd/tap.py", line 51, in create_root
2017-01-04 14:07:26.388083 [-]     configure_django(settings)
2017-01-04 14:07:26.388497 [-]   File "/vagrant/slyd/slyd/tap.py", line 44, in configure_django
2017-01-04 14:07:26.389670 [-]     django.setup()
2017-01-04 14:07:26.390073 [-]   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 22, in setup
2017-01-04 14:07:26.390376 [-]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2017-01-04 14:07:26.390733 [-]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
2017-01-04 14:07:26.391094 [-]     self._setup(name)
2017-01-04 14:07:26.391441 [-]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
2017-01-04 14:07:26.391798 [-]     self._wrapped = Settings(settings_module)
2017-01-04 14:07:26.392123 [-]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
2017-01-04 14:07:26.392453 [-]     mod = importlib.import_module(self.SETTINGS_MODULE)
2017-01-04 14:07:26.392795 [-]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
2017-01-04 14:07:26.393157 [-]     __import__(name)
2017-01-04 14:07:26.393623 [-] ImportError: No module named portia_server.settings

```

**Comment by ruairif** [comment]
If you run:
```bash
export PYTHONPATH='/app/portia_server:/app/slyd:/app/slybot'
/app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist & /app/portia_server/manage.py runserver
```
Does it work?

**Comment by wildgarden** [comment]
The error is gone, when after adding the PYTHONPATH. However, I had to change the path since I use Vagrant. Thus `app` == `vagrant` .
Morevover the `/portiaui/dist` was missing. Building as proposed in #674 failed in node postinstall. This failure might be due to the use of legacy binary "node".

**Comment by ruairif** [comment]
Thank you for the full list of what you needed to change. I'll add it to the docs when I'm updating them.
