### ISSUE TITLE
Running Portia spiders gives error

### ISSUE THREAD

**Issue by eng1neer** [scrapinghub/portia#671]
When trying to run Portia spider (green arrow button on the screenshot) it errors with the following stacktrace:

<img width="312" alt="screen shot 2017-01-05 at 20 48 27" src="https://cloud.githubusercontent.com/assets/1079094/21689009/5e6b2888-d388-11e6-932f-41e70df4b6a0.png">

```
Internal Server Error: /api/projects/test/spiders/demo.test.com/schedule
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/app/portia_server/portia_api/resources/route.py", line 73, in dispatch
    return super(JsonApiRoute, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/app/portia_server/portia_api/resources/route.py", line 76, in handle_exception
    response = super(JsonApiRoute, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/portia_server/portia_api/resources/spiders.py", line 74, in schedule
    schedule_data = self._schedule_data()
TypeError: _schedule_data() takes exactly 3 arguments (1 given)
```

What are the possible ways to run a Portia spider? Is there a way to run a spider on Scrapinghub's Cloud and locally?

On the scrapinghub.com there is no "Run this spider" option, but there is a "publish project" option instead. What are the differences between the two?

**Comment by ruairif** [comment]
`Publish project` is a way to set the current state of your project as the version that will be used when you run spiders from app.scrapinghub.com. `Run this spider` allows you to run the spider in its current state so you can run a test crawl as you're building your spider to see how well it crawls.

You should be able to run your spiders locally by using [scrapyd](https://scrapyd.readthedocs.io/en/stable/), if you pull the latest updates to the branch you used earlier. You may need to set the `eggs_dir` in the settings for scrapyd and/or use scrapyd deploy

You can also run you spider locally by changing into the directory that your project is stored in and running:
`portiacrawl . SPIDERNAME`

Running a spider locally and on ScrapyCloud isn't possible from the UI at the moment but it would be possible to add support for this if needed. You can try running it on ScrapyCloud by doing something similar to [this](http://help.scrapinghub.com/portia/how-to-build-a-custom-portia-image-for-a-given-project-bundle)

**Comment by eng1neer** [comment]
@ruairif thank you for the explanation.

When trying to run `portiacrawl .` in a project's directory I get 

```
IOError: [Errno 2] No such file or directory: './extractors.json'
```

Any ideas what can be wrong?

**Comment by eng1neer** [comment]
After creating an `extractors.json` with `{}` content I got it running

**Comment by ruairif** [comment]
I'll look into why that isn't created by default and make a fix

**Comment by eng1neer** [comment]
Not sure whether this is the right place to ask, but when running Portia spider on `scrapyd` instance I get the following log:

```
2017-01-06 16:01:15 [scrapy.utils.log] INFO: Scrapy 1.3.0 started (bot: scrapybot)
2017-01-06 16:01:15 [scrapy.utils.log] INFO: Overridden settings: {'FEED_URI': 'file:///var/lib/scrapyd/items/test/demo.test.com/578f5ae2d42911e69f500242ac120002.jl', 'LOG_FILE': '/var/lib/scrapyd/logs/test/demo.test.com/578f5ae2d42911e69f500242ac120002.log', 'DUPEFILTER_CLASS': 'scrapyjs.SplashAwareDupeFilter'}
2017-01-06 16:01:15 [py.warnings] WARNING: /usr/local/lib/python2.7/dist-packages/slybot/closespider.py:10: ScrapyDeprecationWarning: Importing from scrapy.xlib.pydispatch is deprecated and will no longer be supported in future Scrapy versions. If you just want to connect signals use the from_crawler class method, otherwise import pydispatch directly if needed. See: https://github.com/scrapy/scrapy/issues/1762
  from scrapy.xlib.pydispatch import dispatcher

2017-01-06 16:01:15 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2017-01-06 16:01:15 [twisted] CRITICAL: Unhandled error in Deferred:
2017-01-06 16:01:15 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 94, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiders/__init__.py", line 50, in from_crawler
    spider = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/slybot/spidermanager.py", line 51, in __init__
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/slybot/spider.py", line 53, in __init__
    instance.setup_bot(settings, spec, item_schemas, all_extractors)
  File "/usr/local/lib/python2.7/dist-packages/slybot/plugins/scrapely_annotations/annotations.py", line 53, in setup_bot
    ), key=lambda pair: pair[0])
  File "/usr/local/lib/python2.7/dist-packages/slybot/plugins/scrapely_annotations/annotations.py", line 52, in <genexpr>
    for t in spec['templates'] if t.get('page_type', 'item') == 'item'
  File "/usr/local/lib/python2.7/dist-packages/scrapely/htmlpage.py", line 210, in dict_to_page
    body = jsonpage[body_key]
KeyError: 'annotated_body'
```

Any ideas what can be wrong here?

**Comment by ruairif** [comment]
I would guess that the version of slybot on your scrapyd instance is outdated.
Try running `pip install slybot==0.13.0b31` in the environment that scrapyd is installed in

**Comment by eng1neer** [comment]
@ruairif Thank you, indeed I was using an outdated version of slybot, I have upgraded to `0.13.0b31`, and now I get another error. Actually, the error comes up earlier, when uploading project with `scrapyd-deploy`:

```
# docker exec -it scrapyd_scrapyd_1 /bin/sh -c 'cd /app/slyd/slyd/data/projects/test; scrapyd-deploy -p test'
Packing version 1483954262
Deploying to project "test" in http://localhost:6800/addversion.json
Server response (200):
{"status": "error", "message": "KeyError: 'original_body'", "node_name": "e151897085c9"}
```

`scrapyd` output:

```
scrapyd_1   | 2017-01-09T09:31:05+0000 [_GenericHTTPChannelProtocol,1,127.0.0.1] Unhandled Error
scrapyd_1   | 	Traceback (most recent call last):
scrapyd_1   | 	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1845, in allContentReceived
scrapyd_1   | 	    req.requestReceived(command, path, version)
scrapyd_1   | 	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 766, in requestReceived
scrapyd_1   | 	    self.process()
scrapyd_1   | 	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 190, in process
scrapyd_1   | 	    self.render(resrc)
scrapyd_1   | 	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 241, in render
scrapyd_1   | 	    body = resrc.render(self)
scrapyd_1   | 	--- <exception caught here> ---
scrapyd_1   | 	  File "/usr/local/lib/python2.7/dist-packages/scrapyd/webservice.py", line 21, in render
scrapyd_1   | 	    return JsonResource.render(self, txrequest).encode('utf-8')
scrapyd_1   | 	  File "/usr/local/lib/python2.7/dist-packages/scrapyd/utils.py", line 20, in render
scrapyd_1   | 	    r = resource.Resource.render(self, txrequest)
scrapyd_1   | 	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
scrapyd_1   | 	    return m(request)
scrapyd_1   | 	  File "/usr/local/lib/python2.7/dist-packages/scrapyd/webservice.py", line 86, in render_POST
scrapyd_1   | 	    spiders = get_spider_list(project, version=version)
scrapyd_1   | 	  File "/usr/local/lib/python2.7/dist-packages/scrapyd/utils.py", line 136, in get_spider_list
scrapyd_1   | 	    raise RuntimeError(msg.splitlines()[-1])
scrapyd_1   | 	exceptions.RuntimeError: KeyError: 'original_body'
```

I'm using https://hub.docker.com/r/vimagick/scrapyd docker image which seems to use the latest versions of `scrapy`, `scrapyd` and `scrapyd-client`

Any other dependencies that worth checking?

**Comment by eng1neer** [comment]
It appeared that the original error is being thrown at [builder.py](https://github.com/scrapinghub/portia/blob/3dbb01c0fda0ac945240231833a2633e319aaff2/slybot/slybot/plugins/scrapely_annotations/builder.py#L56) when it couldn't find `original_body` key in a `template` dictionary. My `template` variable contents is as follows:

```
{u'extractors': {}, u'name': u'Video Games X-Box One X-Box One', u'url': u'http://demo.cs-cart.com/stores/2a68082ae8bb0818/video-games/x-box-one/x-box-one/', u'scrapes': u'680e-4681-9b03', u'spider': u'demo.cs-cart.com', u'version': u'0.13.0b31', u'page_type': u'item', u'plugins': {u'annotations-plugin': {u'extracts': [{u'container_id': None, u'tagid': None, u'required': [], u'schema_id': u'680e-4681-9b03', u'id': u'464f-400d-84b8', u'repeated': False, u'item_container': True, u'text-content': '#portia-content', u'siblings': 0, u'selector': u'.ty-product-block__left > .cm-disable-empty-files', u'annotations': {'#portia-content': '#dummy'}}, {u'xpath': u'//*[contains(concat(" ", @class, " "), " ty-product-block__left ")]/*[contains(concat(" ", @class, " "), " cm-disable-empty-files ")]/*[contains(concat(" ", @class, " "), " ty-product-block-title ")]', u'reject_selectors': [], u'required': [], u'tagid': None, u'selection_mode': u'auto', u'container_id': u'464f-400d-84b8', u'accept_selectors': [u'.ty-product-block-title'], u'post_text': None, u'repeated': False, 'annotations': {u'content': [{'id': u'e4d2-4a60-8f6c|4e87-445b-b356', u'attribute': u'content', u'required': False, u'field': u'6ee9-40f1-b54b', u'extractors': {}}]}, u'pre_text': None, u'data': {u'4e87-445b-b356': {'id': u'e4d2-4a60-8f6c|4e87-445b-b356', u'attribute': u'content', u'required': False, u'field': u'6ee9-40f1-b54b', u'extractors': {}}}, u'id': u'e4d2-4a60-8f6c', u'selector': u'.ty-product-block__left > .cm-disable-empty-files > .ty-product-block-title'}]}}, u'page_id': u'', u'id': u'6a0d-43d3-a066'}
```

It clearly doesn't have `body` nor `original_body` key in it. Any clue on why could that be the case?

**Comment by ruairif** [comment]
The body and original_body key should no longer be stored in the file and instead be added in by the builder. Can you upload the project you're using so I can recreate the error myself?

**Comment by eng1neer** [comment]
@ruairif This is the sample project I created with Portia (`develop` branch + #670 changes) that reproduces the error for me:

[amazon.zip](https://github.com/scrapinghub/portia/files/694163/amazon.zip)

**Comment by ruairif** [comment]
Reopening the sample in the UI fixes it for now but I will be making a more robust fix in the coming week
