### ISSUE TITLE
502 Bad Gateway with Docker Image

### ISSUE THREAD

**Issue by justnoise** [scrapinghub/portia#699]
On a Mac running OSX 10.11 I install and run the docker container running the commands in the docs:

When I `docker run` with the commands from the docs I see the following when the server starts up:

```
2017-02-09 03:43:00.606718 [-] Traceback (most recent call last):
2017-02-09 03:43:00.606898 [-]   File "/app/slyd/bin/slyd", line 28, in <module>
2017-02-09 03:43:00.607311 [-]     splash.server.main(server_factory=make_server, argv=[])
2017-02-09 03:43:00.607807 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 372, in main
2017-02-09 03:43:00.608503 [-]     server_factory=server_factory,
2017-02-09 03:43:00.608762 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 291, in default_splash_server
2017-02-09 03:43:00.609236 [-]     argument_cache_max_entries=argument_cache_max_entries,
2017-02-09 03:43:00.609671 [-]   File "/app/slyd/bin/slyd", line 25, in make_server
2017-02-09 03:43:00.610124 [-]     'docroot': opts.root}))
2017-02-09 03:43:00.610556 [-]   File "/app/slyd/slyd/tap.py", line 88, in makeService
2017-02-09 03:43:00.610973 [-]     root = create_root(config, settings_module)
2017-02-09 03:43:00.611358 [-]   File "/app/slyd/slyd/tap.py", line 61, in create_root
2017-02-09 03:43:00.611821 [-]     for file_name in listdir(config['docroot']):
2017-02-09 03:43:00.612268 [-] OSError: [Errno 2] No such file or directory: '/app/portiaui/dist'
Performing system checks...

System check identified no issues (0 silenced).

You have 12 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, contenttypes, db_repo, sessions.
Run 'python manage.py migrate' to apply them.

February 09, 2017 - 03:43:01
Django version 1.10.1, using settings 'portia_server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

When trying to connect to localhost:9001 I get a 502 error from nginx when trying to connect to the root and I get a 404 when trying to connect to `http://localhost:9001/static/index.html`

**Comment by ruairif** [comment]
@justnoise Can you try using the new instructions and scripts here: https://github.com/scrapinghub/portia/pull/700

**Comment by justnoise** [comment]
Hi @ruairif.  Thanks for taking a look at this issue!

I tried the instructions that use the scrapinghub/portia container.  When connecting to http://localhost:9001 I get a 404.  When connecting to http://localhost:9001/static/index.html I get a traceback that shows that it can't connect to MySQL (`mysql.connector.errors.InterfaceError: 2003: Can't connect to MySQL server on '33.33.33.51:3306' (111 Connection refused)`).  That isn't too surprising since the container isn't running MySQL.

I'm going to give a shot at the updated instructions for Vagrant and running locally.  Let me know if I can get you additional information or do anything else to help.

**Comment by ruairif** [comment]
@justnoise Can you give me the full traceback for the MySQL issue?

**Comment by Jacobh2** [comment]
Hi @ruairif 

I checkout the branch `update_installation`, in order to get the changes you proposed in https://github.com/scrapinghub/portia/pull/700/files for the Dockerfile.

I built using: `docker build -t portia:2 .` which seemed to work nice. I then run it using `docker run -it --rm -v /tmp:/app/data/projects:rw -p 9001:9001 portia:2` which gives me the following output:

```
+ action=
+ shift
+ '[' -z '' ']'
+ _run
+ service nginx start
+ _set_env
+ path=/app/portia_server:/app/slyd:/app/slybot
+ export PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ echo /app/portia_server:/app/slyd:/app/slybot
/app/portia_server:/app/slyd:/app/slybot
+ /app/portia_server/manage.py runserver
+ /app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist
2017-02-17 12:55:58+0000 [-] Log opened.
2017-02-17 12:55:58.596842 [-] Splash version: 2.3.1
2017-02-17 12:55:58.597805 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-02-17 12:55:58.598003 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-02-17 12:55:58.598452 [-] Python 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
2017-02-17 12:55:58.598912 [-] Open files limit: 1048576
2017-02-17 12:55:58.599171 [-] Can't bump open files limit
2017-02-17 12:55:58.824787 [-] Xvfb is started: ['Xvfb', ':40910119', '-screen', '0', '1024x768x24']
2017-02-17 12:56:00.500999 [-] Traceback (most recent call last):
2017-02-17 12:56:00.501414 [-]   File "/app/slyd/bin/slyd", line 28, in <module>
2017-02-17 12:56:00.502279 [-]     splash.server.main(server_factory=make_server, argv=[])
2017-02-17 12:56:00.502794 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 372, in main
2017-02-17 12:56:00.503494 [-]     server_factory=server_factory,
2017-02-17 12:56:00.503963 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 291, in default_splash_server
2017-02-17 12:56:00.504556 [-]     argument_cache_max_entries=argument_cache_max_entries,
2017-02-17 12:56:00.504918 [-]   File "/app/slyd/bin/slyd", line 25, in make_server
2017-02-17 12:56:00.505359 [-]     'docroot': opts.root}))
2017-02-17 12:56:00.505737 [-]   File "/app/slyd/slyd/tap.py", line 88, in makeService
2017-02-17 12:56:00.506152 [-]     root = create_root(config, settings_module)
2017-02-17 12:56:00.506541 [-]   File "/app/slyd/slyd/tap.py", line 61, in create_root
2017-02-17 12:56:00.506967 [-]     for file_name in listdir(config['docroot']):
2017-02-17 12:56:00.507436 [-] OSError: [Errno 2] No such file or directory: '/app/portiaui/dist'
Performing system checks...

System check identified no issues (0 silenced).

You have 12 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, contenttypes, db_repo, sessions.
Run 'python manage.py migrate' to apply them.

February 17, 2017 - 12:56:01
Django version 1.10.5, using settings 'portia_server.settings'
Starting development server at http://127.0.0.1:8000/
```

When I try to browse to `localhost:9001` I still get a 502 Bad Gateway error. And pointing it to `http://localhost:9001/static/index.html` gives me a 404, just as @justnoise experienced.

**Comment by ruairif** [comment]
You are missing the assets. I've described the full process here: https://github.com/scrapinghub/portia/issues/701#issuecomment-280086657 
I'll update the PR to match those instructions if they work for you too

**Comment by Jacobh2** [comment]
Thank you very much! That did the trick! 

Here are the full steps I did to make it work!
1. `mkdir portia`
2. `cd portia`
3. `git clone https://github.com/scrapinghub/portia.git`
4. `cd portia`
5. `git checkout update_installation`
6. `mkdir ~/data`
7. `cd portiaui`
8. `npm install && bower install`
9. `cd node_modules/ember-cli && npm install && cd ../../ && ember build`
10. `cd ..`
11. `docker build -t portia:v1 .`
12. `docker run -i -t --rm -p 9001:9001 -v ~/data:/app/data/projects ~/portia/portia/portiaui/dist:/app/portiaui/dist portia:v1`
13. Point a browser to `localhost:9001`

**Comment by ruairif** [comment]
Portia can now be installed and run with docker simply by running:

    docker run -v ~/portia_projects:/app/data/projects:rw -p 9001:9001 scrapinghub/portia
