### ISSUE TITLE
How to install portia2.0 correctly by docker?

### ISSUE THREAD

**Issue by ChoungJX** [scrapinghub/portia#701]
when I install portia by docker I had a problems.
when I run  `ember build -w` ,the results is:

> Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
components/browser-iframe.js: line 175, col 39, 'TreeMirror' is not defined.
components/browser-iframe.js: line 212, col 9, '$' is not defined.
components/browser-iframe.js: line 227, col 23, '$' is not defined.
components/browser-iframe.js: line 281, col 20, '$' is not defined.
4 errors
components/inspector-panel.js: line 92, col 16, '$' is not defined.
components/inspector-panel.js: line 92, col 33, '$' is not defined.
components/inspector-panel.js: line 102, col 16, '$' is not defined.
3 errors
components/save-status.js: line 48, col 16, 'moment' is not defined.
1 error
controllers/projects/project/conflicts/conflict.js: line 105, col 13, '$' is not defined.
1 error
controllers/projects/project/spider.js: line 10, col 25, 'URI' is not defined.
1 error
routes/projects/project/conflicts.js: line 5, col 16, '$' is not defined.
1 error
services/web-socket.js: line 10, col 15, 'URI' is not defined.
services/web-socket.js: line 15, col 12, 'URI' is not defined.
2 errors
utils/browser-features.js: line 14, col 13, 'Modernizr' is not defined.
1 error
utils/tree-mirror-delegate.js: line 30, col 20, '$' is not defined.
utils/tree-mirror-delegate.js: line 66, col 17, '$' is not defined.
2 errors
utils/utils.js: line 15, col 20, 'URI' is not defined.
utils/utils.js: line 50, col 9, 'Raven' is not defined.
utils/utils.js: line 56, col 9, 'Raven' is not defined.
3 errors
===== 10 JSHint Errors
Build successful - 1641ms.
Slowest Trees                                 | Total               
----------------------------------------------+---------------------
broccoli-persistent-filter:Babel > [Babel:... | 275ms               
JSHint app                                    | 149ms               
SourceMapConcat: Concat: Vendor /assets/ve... | 89ms                
broccoli-persistent-filter:Babel              | 85ms                
broccoli-persistent-filter:Babel              | 82ms                
Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
broccoli-persistent-filter:Babel > [Ba... (2) | 294ms (147 ms)      
broccoli-persistent-filter:Babel (5)          | 257ms (51 ms)       
JSHint app (1)                                | 149ms               
SourceMapConcat: Concat: Vendor /asset... (1) | 89ms                
broccoli-persistent-filter:TemplateCom... (2) | 88ms (44 ms)

I wanna know where is wrong.
By the way,this step I followed the some ISSUES,if I just follow the Documentation to install portia by docker(`docker build -t portia .`),when I run the portia,the http://localhost:9001/static/index.html will show me nothing.
So,how to install portia2.0 correctly by docker?Could someone help me?

**Comment by ruairif** [comment]
What happens if you visit: `http://localhost:9001`

**Comment by ChoungJX** [comment]
visit:`http://localhost:9001`,It show me :` No file` 
By the way: I try to use [https://github.com/scrapinghub/portia/issues/635](url) (#635) way to install portia
but when I run `ember` build -e `production`  
I met a problem:

> Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
⠋ BuildingCould not require 'ember-cli-build.js': Cannot find module 'ember-cli/node_modules/broccoli-source'
Error: Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/node_modules/broccoli-source'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jax/portia/portiaui/ember-cli-build.js:3:69)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

How to solve it? Thanks.

**Comment by ruairif** [comment]
Can you try `cd node_modules/ember-cli && npm install && cd ../../ && ember build`

**Comment by AlexTan-b-z** [comment]
I'm same with you!@ChoungJX 
Yes, after I tried the `cd node_modules/ember-cli && npm install && cd ../../ && ember build`,there is 
`Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
⠹ Building[BABEL] Note: The code generator has deoptimised the styling of "portia-ui/templates/components/project-structure-listing.js" as it exceeds the max of "100KB".
⠧ Building[BABEL] Note: The code generator has deoptimised the styling of "portia-ui/tests/unit/utils/selectors-test.js" as it exceeds the max of "100KB".
Built project successfully. Stored in "dist/".`

There is no error. But the page`http://localhost:9001/` show me `No file`, too.
@ruairif How to solve it? Thanks.

**Comment by AlexTan-b-z** [comment]
By the way, when I visited `http://localhost:9001/`
There are some 404:
`2017-02-14 11:51:18.144181 [-] "127.0.0.1" - - [14/Feb/2017:11:51:17 +0000] "GET / HTTP/1.1" 200 1509 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-14 11:51:18.171775 [-] "127.0.0.1" - - [14/Feb/2017:11:51:17 +0000] "GET /assets/vendor.css HTTP/1.1" 200 - "http://localhost:9001/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-14 11:51:18.178994 [-] "127.0.0.1" - - [14/Feb/2017:11:51:17 +0000] "GET /assets/portia-ui.css HTTP/1.1" 200 192777 "http://localhost:9001/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-14 11:51:18.188814 [-] "127.0.0.1" - - [14/Feb/2017:11:51:17 +0000] "GET /assets/portia-ui.js HTTP/1.1" 200 1751263 "http://localhost:9001/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-14 11:51:18.196500 [-] "127.0.0.1" - - [14/Feb/2017:11:51:17 +0000] "GET /assets/vendor.js HTTP/1.1" 200 3315636 "http://localhost:9001/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-14 11:51:18.770235 [-] "127.0.0.1" - - [14/Feb/2017:11:51:17 +0000] "GET /favicon.ico HTTP/1.1" 404 153 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-14 11:51:18.824134 [-] "127.0.0.1" - - [14/Feb/2017:11:51:18 +0000] "GET /api/projects HTTP/1.1" 404 153 "http://localhost:9001/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"`

**Comment by ChoungJX** [comment]
Hello,today,I try the `cd node_modules/ember-cli && npm install && cd ../../ && ember build`   and I run portia again. but when I visit: `http://localhost:9001/static/index.html` or `http://localhost:9001`  there are just blank.  And I have the same wrong:
```
WARNING: Node v7.5.0 has currently not been tested against Ember CLI and may result in unexpected behaviour.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
⠸ Building[BABEL] Note: The code generator has deoptimised the styling of "portia-ui/templates/components/project-structure-listing.js" as it exceeds the max of "100KB".
⠴ Building[BABEL] Note: The code generator has deoptimised the styling of "portia-ui/tests/unit/utils/selectors-test.js" as it exceeds the max of "100KB".
Built project successfully. Stored in "dist/".
```
Then I try the branch `update_installation` to install and run portia,It's seem had updated the `provision.sh`
But  when I visit: `http://localhost:9001/static/index.html` or `http://localhost:9001`  It's show me:
`No Such Resource`
Could you help me again?

**Comment by ruairif** [comment]
What command are you using to run docker?

**Comment by ruairif** [comment]
I ran:

    mkdir ~/data
    git clone git@github.com:scrapinghub/portia.git
    cd portia/portiaui
    npm install && bower install
    cd node_modules/ember-cli && npm install && cd ../../ && ember build
    docker build . -t portia
    docker run -i -t --rm -p 9001:9001 -v ~/data:/app/data/projects ~/portia/portiaui/dist:/app/portiaui/dist portia

**Comment by ChoungJX** [comment]
I install portia successfully today.When I visit:`127.0.0.1:9001`,I can see:`What would you like to work on today`  
I didn't run `mkdir ~/data` at previous time,maybe this is the cause of the error.
Thank you very much!
Now I have a little problem:It told me to run: `python manage.py migrate`,Is the step important?

**Comment by ruairif** [comment]
It should work fine without it. It only matters if you're using the Git-SQL backend which is not the default

**Comment by ChoungJX** [comment]
Thank you!All the problems are solved.Wish portia better and better.
ありがとうございました!(Thank you!)

**Comment by nbah07** [comment]
Now seems to be working, apparently. But the address localhost:9001 gets a blank page on both commands, detailed below
```
$ sudo docker run -it --rm -v ~/opt/portia/data/projects:/app/data/projects:rw -p 9001:9001 portia
+ action=
+ shift
+ '[' -z '' ']'
+ _run
+ service nginx start
+ _set_env
+ path=/app/portia_server:/app/slyd:/app/slybot
+ export PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ echo /app/portia_server:/app/slyd:/app/slybot
/app/portia_server:/app/slyd:/app/slybot
+ /app/portia_server/manage.py runserver
+ /app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist
2017-02-21 15:26:44+0000 [-] Log opened.
2017-02-21 15:26:44.335007 [-] Splash version: 2.3.1
2017-02-21 15:26:44.356947 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-02-21 15:26:44.357184 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-02-21 15:26:44.357701 [-] Python 2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]
2017-02-21 15:26:44.357981 [-] Open files limit: 65536
2017-02-21 15:26:44.359016 [-] Can't bump open files limit
2017-02-21 15:26:44.496404 [-] Xvfb is started: ['Xvfb', ':1061776413', '-screen', '0', '1024x768x24']
2017-02-21 15:26:49.526291 [-] Site starting on 9002
2017-02-21 15:26:49.526592 [-] Starting factory <slyd.server.Site instance at 0xae81316c>
Performing system checks...

System check identified no issues (0 silenced).

You have 12 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, contenttypes, db_repo, sessions.
Run 'python manage.py migrate' to apply them.

February 21, 2017 - 15:26:52
Django version 1.10.1, using settings 'portia_server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
2017-02-21 15:27:10.809394 [-] "127.0.0.1" - - [21/Feb/2017:15:27:10 +0000] "GET / HTTP/1.0" 200 1509 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-21 15:27:12.671249 [-] "127.0.0.1" - - [21/Feb/2017:15:27:12 +0000] "GET /favicon.ico HTTP/1.0" 404 153 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-21 15:27:45.401236 [-] "127.0.0.1" - - [21/Feb/2017:15:27:44 +0000] "GET / HTTP/1.0" 304 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"
```
```
$ sudo docker run -it --rm -p 9001:9001 \
>     -v ~/opt/portia/data/projects:/app/data/projects:rw \
>     -v ~/Downloads/src/portia/portiaui/dist:/app/portiaui/dist \
>     -v ~/Downloads/src/portia/slyd:/app/slyd \
>     -v ~/Downloads/src/portia/portia_server:/app/portia_server \
>     portia
+ action=
+ shift
+ '[' -z '' ']'
+ _run
+ service nginx start
+ _set_env
+ path=/app/portia_server:/app/slyd:/app/slybot
+ export PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ echo /app/portia_server:/app/slyd:/app/slybot
/app/portia_server:/app/slyd:/app/slybot
+ /app/portia_server/manage.py runserver
+ /app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist
2017-02-21 15:56:45+0000 [-] Log opened.
2017-02-21 15:56:45.172213 [-] Splash version: 2.3.1
2017-02-21 15:56:45.173466 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-02-21 15:56:45.173808 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-02-21 15:56:45.174244 [-] Python 2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]
2017-02-21 15:56:45.174527 [-] Open files limit: 65536
2017-02-21 15:56:45.174810 [-] Can't bump open files limit
2017-02-21 15:56:45.304312 [-] Xvfb is started: ['Xvfb', ':1789828857', '-screen', '0', '1024x768x24']
2017-02-21 15:56:47.608780 [-] Site starting on 9002
2017-02-21 15:56:47.609943 [-] Starting factory <slyd.server.Site instance at 0xae88216c>
Performing system checks...

System check identified no issues (0 silenced).
Unhandled exception in thread started by <function wrapper at 0xb5231304>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 437, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 209, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
2017-02-21 15:57:37.554128 [-] "127.0.0.1" - - [21/Feb/2017:15:57:36 +0000] "GET / HTTP/1.0" 200 1509 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"
```

**Comment by ruairif** [comment]
What if you try?
```bash
sudo docker run -it --rm -p 9001:9001 \
     -v ~/opt/portia/data/projects:/app/data/projects:rw \
     -v ~/Downloads/src/portia/portiaui/dist:/app/portiaui/dist \
     -v ~/Downloads/src/portia/slyd:/app/slyd \
     -v ~/Downloads/src/portia/portia_server:/app/portia_server:rw \
     portia
```
(note the rw for portia_server)

**Comment by nbah07** [comment]
I looked at ChoungJX post: must ask if is it necessary to `mkdir ~/data` at begining?
```
$ sudo docker run -it --rm -p 9001:9001 \
> -v ~/opt/portia/data/projects:/app/data/projects:rw \
> -v ~/Downloads/src/portia/portiaui/dist:/app/portiaui/dist \
> -v ~/Downloads/src/portia/slyd:/app/slyd \
> -v ~/Downloads/src/portia/portia_server:/app/portia_server:rw \
> portia
[sudo] password for capum: 
+ action=
+ shift
+ '[' -z '' ']'
+ _run
+ service nginx start
+ _set_env
+ path=/app/portia_server:/app/slyd:/app/slybot
+ export PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ echo /app/portia_server:/app/slyd:/app/slybot
/app/portia_server:/app/slyd:/app/slybot
+ /app/portia_server/manage.py runserver
+ /app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist
2017-02-27 01:23:20+0000 [-] Log opened.
2017-02-27 01:23:20.981847 [-] Splash version: 2.3.1
2017-02-27 01:23:21.053713 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-02-27 01:23:21.053921 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-02-27 01:23:21.054280 [-] Python 2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]
2017-02-27 01:23:21.054734 [-] Open files limit: 65536
2017-02-27 01:23:21.055059 [-] Can't bump open files limit
2017-02-27 01:23:21.423421 [-] Xvfb is started: ['Xvfb', ':47714373', '-screen', '0', '1024x768x24']
2017-02-27 01:23:33.172713 [-] Site starting on 9002
2017-02-27 01:23:33.172982 [-] Starting factory <slyd.server.Site instance at 0xae89e16c>
Performing system checks...

System check identified no issues (0 silenced).
Unhandled exception in thread started by <function wrapper at 0xb5230374>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 437, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 209, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
2017-02-27 01:24:19.214340 [-] "127.0.0.1" - - [27/Feb/2017:01:24:19 +0000] "GET / HTTP/1.0" 200 1509 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-27 01:24:21.237404 [-] "127.0.0.1" - - [27/Feb/2017:01:24:21 +0000] "GET /favicon.ico HTTP/1.0" 404 153 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-27 01:24:21.255567 [-] "127.0.0.1" - - [27/Feb/2017:01:24:21 +0000] "GET /favicon.ico HTTP/1.0" 404 153 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"
```

**Comment by ChoungJX** [comment]
I‘m not sure.You can try 
`sudo docker run -i -t --rm -v ~/data:/app/slyd/slyd/data/projects:rw -v ~/portia/portiaui/dist:/app/portiaui/dist -p 9001:9001 portia` 
to run portia

**Comment by nbah07** [comment]
less error i guess, still localhost:9001 gets blank page.
```
$ sudo docker run -it --rm -p 9001:9001 \
> -v ~/data:/app/slyd/slyd/data/projects:rw \
> -v ~/Downloads/src/portia/portiaui/dist:/app/portiaui/dist \
> portia
[sudo] password for capum: 
+ action=
+ shift
+ '[' -z '' ']'
+ _run
+ service nginx start
+ _set_env
+ path=/app/portia_server:/app/slyd:/app/slybot
+ export PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ echo /app/portia_server:/app/slyd:/app/slybot
/app/portia_server:/app/slyd:/app/slybot
+ /app/portia_server/manage.py runserver
+ /app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist
2017-02-27 09:52:14+0000 [-] Log opened.
2017-02-27 09:52:14.068813 [-] Splash version: 2.3.1
2017-02-27 09:52:14.070150 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-02-27 09:52:14.070434 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-02-27 09:52:14.070716 [-] Python 2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]
2017-02-27 09:52:14.071153 [-] Open files limit: 65536
2017-02-27 09:52:14.071576 [-] Can't bump open files limit
2017-02-27 09:52:14.265151 [-] Xvfb is started: ['Xvfb', ':993014950', '-screen', '0', '1024x768x24']
2017-02-27 09:52:16.867762 [-] Site starting on 9002
2017-02-27 09:52:16.868021 [-] Starting factory <slyd.server.Site instance at 0xae87816c>
Performing system checks...

System check identified no issues (0 silenced).

You have 12 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, contenttypes, db_repo, sessions.
Run 'python manage.py migrate' to apply them.

February 27, 2017 - 09:52:18
Django version 1.10.1, using settings 'portia_server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
2017-02-27 09:52:43.484941 [-] "127.0.0.1" - - [27/Feb/2017:09:52:42 +0000] "GET /favicon.ico HTTP/1.0" 404 153 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"
```

**Comment by ChoungJX** [comment]
Did you 
```
cd portia/portiaui
npm install && bower install
cd node_modules/ember-cli && npm install && cd ../../ && ember build
```
??
These steps are very important.

**Comment by ruairif** [comment]
Portia can now be installed with docker simply by running:

    docker run -v ~/portia_projects:/app/data/projects:rw -p 9001:9001 scrapinghub/portia

**Comment by nbah07** [comment]
@ruairif hello, am I unsupported cause my host lubuntu is 32 bit? this image won't run on my current system.
I managed to view the front page of localhost:9001 after building a new image with the Dockerfile from porita.git; which I changed, in Dockerfile, the first line: `FROM ubuntu:14.04` to a image id of a 32 bit ubuntu (ioft/i386-ubuntu). Meanwhile the size dropped from 1 GB to 734 MB. Anyway I couldn't get to pass the frontpage, the naming creation of a new project, in it, failed imediately. I am getting somewhere?
```
$ docker run -v ~/portia_projects:/app/data/projects:rw -p 9001:9001 scrapinghub/portia
Unable to find image 'scrapinghub/portia:latest' locally
latest: Pulling from scrapinghub/portia
c60055a51d74: Pull complete 
755da0cdb7d2: Pull complete 
969d017f67e6: Pull complete 
37c9a9113595: Pull complete 
a3d9f8479786: Pull complete 
c950e8155cb9: Pull complete 
eba39be7aaef: Pull complete 
086f4ce28fd2: Pull complete 
6fb4b8c14322: Pull complete 
94d6b29d7c64: Pull complete 
deb8acc6a07a: Pull complete 
33d8ae0ebc35: Pull complete 
de74bbe19625: Pull complete 
d4ee32f6b2f8: Pull complete 
Digest: sha256:1676498c8f014da05a88aeadfef7b6e546af1121755d151cc76c6a6d21696200
Status: Downloaded newer image for scrapinghub/portia:latest
panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:178: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x835c220, 0x97586a00)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x326
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction.func1(0x97581974)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:478 +0x2c1
panic(0x835c220, 0x97586a00)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x3fd
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x975815fc, 0x974e02b0, 0x97581684)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0xfd
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x97550240, 0x86b464b8, 0x97586a00)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x474
main.glob.func8(0x9754c320, 0x0, 0x0)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/main_unix.go:26 +0x57
reflect.Value.call(0x8302700, 0x842f7c0, 0x13, 0x838d7b8, 0x4, 0x97581934, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/go-1.6/src/reflect/value.go:435 +0xeeb
reflect.Value.Call(0x8302700, 0x842f7c0, 0x13, 0x97581934, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/reflect/value.go:303 +0x8c
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction(0x8302700, 0x842f7c0, 0x9754c320, 0x0, 0x0)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:487 +0x25f
github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run(0x838fcd8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x840e120, 0x51, 0x0, ...)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:191 +0xda7
github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0x9753e240, 0x9751e050, 0x2, 0x2, 0x0, 0x0)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:240 +0x92b
main.main()
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/main.go:132 +0xa60
```
