### ISSUE TITLE
Not able to install portia locally for Debian based OS

### ISSUE THREAD

**Issue by satwikkansal** [scrapinghub/portia#702]
While following the instructions given in the [docs](http://portia.readthedocs.io/en/latest/installation.html#debian) 

I'm getting the following error

```
E: Failed to fetch http://ppa.launchpad.net/beineri/opt-qt551-trusty/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Command failed (exitcode: 100), exiting...
```
I tried removing the `ppa` and trying it again but seems like this `beineri ppa` is being used by any dependency in `provision.sh`, So it is automatically added when I run `install_splash` function of the `provision.sh`. 
Any idea how to get around with it?

Operating system : Ubuntu 16.04

**Comment by ruairif** [comment]
https://github.com/scrapinghub/portia/pull/700/files
Can you try using the instructions here and use either vagrant or docker to install Portia?

**Comment by satwikkansal** [comment]
@ruairif 

Getting I was getting this error with vagarant
```
==> default: install -m 755 -p /builds/PyQt-gpl-5.5.1/pyuic5 /usr/bin/
==> default: /builds /tmp/splash-2.2.x
==> default: /tmp/splash-2.2.x
==> default: Unpacking /tmp/splash-2.2.x
==> default:   Running setup.py (path:/tmp/pip-kXkL2G-build/setup.py) egg_info for package from file:///tmp/splash-2.2.x
==> default:     
==> default:     warning: no files found matching '*.rst' under directory 'splash/lua_modules'
==> default:     warning: no files found matching '*.txt' under directory 'splash/lua_modules'
==> default:     warning: no files found matching '*.js' under directory 'splash/vendor/harviewer/webapp'
==> default:     warning: no files found matching '*.html' under directory 'splash/vendor/harviewer/webapp'
==> default:     warning: no files found matching '*.css' under directory 'splash/vendor/harviewer/webapp'
==> default:     warning: no files found matching '*.gif' under directory 'splash/vendor/harviewer/webapp'
==> default:     warning: no files found matching '*.png' under directory 'splash/vendor/harviewer/webapp'
==> default:     warning: no files found matching '*.swf' under directory 'splash/vendor/harviewer/webapp'
==> default:     warning: no files found matching '*.html' under directory 'splash/vendor/harviewer/webapp'
==> default: Downloading/unpacking Twisted<16.3.0 (from splash==2.2.2)
==> default: Cleaning up...
==> default: Exception:
==> default: Traceback (most recent call last):
==> default:   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
==> default:     status = self.run(options, args)
==> default:   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
==> default:     requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
==> default:   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
==> default:     do_download,
==> default:   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
==> default:     self.session,
==> default:   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 572, in unpack_http_url
==> default:     download_hash = _download_url(resp, link, temp_location)
==> default:   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 433, in _download_url
==> default:     for chunk in resp_read(4096):
==> default:   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 421, in resp_read
==> default:     chunk_size, decode_content=False):
==> default:   File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/response.py", line 225, in stream
==> default:     data = self.read(amt=amt, decode_content=decode_content)
==> default:   File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/response.py", line 174, in read
==> default:     data = self._fp.read(amt)
==> default:   File "/usr/lib/python2.7/httplib.py", line 602, in read
==> default:     s = self.fp.read(amt)
==> default:   File "/usr/lib/python2.7/socket.py", line 380, in read
==> default:     data = self._sock.recv(left)
==> default:   File "/usr/lib/python2.7/ssl.py", line 341, in recv
==> default:     return self.read(buflen)
==> default:   File "/usr/lib/python2.7/ssl.py", line 260, in read
==> default:     return self._sslobj.read(len)
==> default: SSLError: The read operation timed out
==> default: Storing debug log for failure in /root/.pip/pip.log
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by ruairif** [comment]
Try rebuilding again. This error seems to be related to a https connection timing out
