### ISSUE TITLE
No such file /app/portiaui/dist

### ISSUE THREAD

**Issue by nbah07** [scrapinghub/portia#710]
I have installed docker.io from ubuntu repository, a 32 bit 16.04 host with a docker image, which I changed in Dockerfile to safe the build 
FROM ioft/i386-ubuntu:14.04
Then I continue what follows in the portia docs: `docker build` = sucessfully.
Got these with similar prompts: #635 and #701 
And similar workarounds (both ruairif), but I couldn't manage to deal with them. I couldn't find `npm install` and `bower install` commands inside the container already built to start off. How to proceed?
I lack much of experience.
Regards

```
$ sudo docker run -it --rm -v /home/username/Downloads/PortiaRepo/data:/app/slyd/data:rw -p 9001:9001 --name porco portia
+ action=
+ shift
+ '[' -z '' ']'
+ _run
+ service nginx start
+ _set_env
+ path=/app/portia_server:/app/slyd:/app/slybot
+ export PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ echo /app/portia_server:/app/slyd:/app/slybot
/app/portia_server:/app/slyd:/app/slybot
+ /app/portia_server/manage.py runserver
+ /app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist
2017-02-20 20:36:25+0000 [-] Log opened.
2017-02-20 20:36:25.997569 [-] Splash version: 2.3.1
2017-02-20 20:36:26.054108 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-02-20 20:36:26.054354 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-02-20 20:36:26.056174 [-] Python 2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]
2017-02-20 20:36:26.056645 [-] Open files limit: 65536
2017-02-20 20:36:26.057257 [-] Can't bump open files limit
2017-02-20 20:36:26.267398 [-] Xvfb is started: ['Xvfb', ':1970934647', '-screen', '0', '1024x768x24']
Performing system checks...

2017-02-20 20:36:32.384535 [-] Traceback (most recent call last):
2017-02-20 20:36:32.385152 [-]   File "/app/slyd/bin/slyd", line 28, in <module>
2017-02-20 20:36:32.385907 [-]     splash.server.main(server_factory=make_server, argv=[])
2017-02-20 20:36:32.386274 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 372, in main
2017-02-20 20:36:32.387001 [-]     server_factory=server_factory,
2017-02-20 20:36:32.387350 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 291, in default_splash_server
2017-02-20 20:36:32.387960 [-]     argument_cache_max_entries=argument_cache_max_entries,
2017-02-20 20:36:32.388277 [-]   File "/app/slyd/bin/slyd", line 25, in make_server
2017-02-20 20:36:32.388705 [-]     'docroot': opts.root}))
2017-02-20 20:36:32.389003 [-]   File "/app/slyd/slyd/tap.py", line 88, in makeService
2017-02-20 20:36:32.389343 [-]     root = create_root(config, settings_module)
2017-02-20 20:36:32.389612 [-]   File "/app/slyd/slyd/tap.py", line 61, in create_root
2017-02-20 20:36:32.389935 [-]     for file_name in listdir(config['docroot']):
2017-02-20 20:36:32.390260 [-] OSError: [Errno 2] No such file or directory: '/app/portiaui/dist'
System check identified no issues (0 silenced).

You have 12 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, contenttypes, db_repo, sessions.
Run 'python manage.py migrate' to apply them.

February 20, 2017 - 20:36:34
Django version 1.10.1, using settings 'portia_server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

**Comment by ruairif** [comment]
`npm` and `bower` should be installed on your host system and then the assets that are build by `ember` in the dist directory are mounted into the container.

You can find more information in the install instructions [here](https://github.com/scrapinghub/portia/blob/4fdb0e81cf9ddda07fb30679c420e02a36ec9de0/docs/installation.rst#developing-portia-using-docker).

**Comment by nbah07** [comment]
i see. but this packages will be install in the host, which, in my case, is a 16.04 ubuntu. Shall it produce any incompatible status?

**Comment by ruairif** [comment]
No. `npm` and `bower` are package managers for javascript and `ember build` is a compiler for javascript and CSS assets.

**Comment by nbah07** [comment]
Now is working, seems to be. But Firefox browser on localhost:9001 gets an blank page
and more below this code block.
```
$ sudo docker run -it --rm -v ~/opt/portia/data/projects:/app/data/projects:rw -p 9001:9001 portia
+ action=
+ shift
+ '[' -z '' ']'
+ _run
+ service nginx start
+ _set_env
+ path=/app/portia_server:/app/slyd:/app/slybot
+ export PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ echo /app/portia_server:/app/slyd:/app/slybot
/app/portia_server:/app/slyd:/app/slybot
+ /app/portia_server/manage.py runserver
+ /app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist
2017-02-21 15:26:44+0000 [-] Log opened.
2017-02-21 15:26:44.335007 [-] Splash version: 2.3.1
2017-02-21 15:26:44.356947 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-02-21 15:26:44.357184 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-02-21 15:26:44.357701 [-] Python 2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]
2017-02-21 15:26:44.357981 [-] Open files limit: 65536
2017-02-21 15:26:44.359016 [-] Can't bump open files limit
2017-02-21 15:26:44.496404 [-] Xvfb is started: ['Xvfb', ':1061776413', '-screen', '0', '1024x768x24']
2017-02-21 15:26:49.526291 [-] Site starting on 9002
2017-02-21 15:26:49.526592 [-] Starting factory <slyd.server.Site instance at 0xae81316c>
Performing system checks...

System check identified no issues (0 silenced).

You have 12 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, contenttypes, db_repo, sessions.
Run 'python manage.py migrate' to apply them.

February 21, 2017 - 15:26:52
Django version 1.10.1, using settings 'portia_server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
2017-02-21 15:27:10.809394 [-] "127.0.0.1" - - [21/Feb/2017:15:27:10 +0000] "GET / HTTP/1.0" 200 1509 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-21 15:27:12.671249 [-] "127.0.0.1" - - [21/Feb/2017:15:27:12 +0000] "GET /favicon.ico HTTP/1.0" 404 153 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"
2017-02-21 15:27:45.401236 [-] "127.0.0.1" - - [21/Feb/2017:15:27:44 +0000] "GET / HTTP/1.0" 304 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"
```
```
$ sudo docker run -i -t --rm -p 9001:9001 \
>     -v ~/opt/portia/data/projects:/app/data/projects:rw \
>     -v ~/portia/portiaui/dist:/app/portiaui/dist \
>     -v ~/portia/slyd:/app/slyd \
>     -v ~/portia/portia_server:/app/portia_server \
>     portia
+ action=
+ shift
+ '[' -z '' ']'
+ _run
+ service nginx start
+ _set_env
+ path=/app/portia_server:/app/slyd:/app/slybot
+ export PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ echo /app/portia_server:/app/slyd:/app/slybot
/app/portia_server:/app/slyd:/app/slybot
+ /app/portia_server/manage.py runserver
/app/docker/entry: line 11: /app/portia_server/manage.py: No such file or directory
+ /app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist
/app/docker/entry: line 10: /app/slyd/bin/slyd: No such file or directory
```
