### ISSUE TITLE
Docker failing to run

### ISSUE THREAD

**Issue by aleixsb** [scrapinghub/portia#722]
docker run -i -t --rm -v $(pwd)/data:/app/slyd/data:rw -p 9001:9001 --name portia portia
+ action=
+ shift
+ '[' -z '' ']'
+ _run
+ service nginx start
+ _set_env
+ path=/app/portia_server:/app/slyd:/app/slybot
+ export PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ echo /app/portia_server:/app/slyd:/app/slybot
/app/portia_server:/app/slyd:/app/slybot
+ /app/portia_server/manage.py runserver
+ /app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist
2017-02-24 10:59:45+0000 [-] Log opened.
2017-02-24 10:59:45.639008 [-] Splash version: 2.3.1
2017-02-24 10:59:45.639295 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-02-24 10:59:45.639399 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-02-24 10:59:45.639442 [-] Python 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
2017-02-24 10:59:45.639484 [-] Open files limit: 1048576
2017-02-24 10:59:45.639516 [-] Can't bump open files limit
2017-02-24 10:59:45.826531 [-] Xvfb is started: ['Xvfb', ':312060088', '-screen', '0', '1024x768x24']
2017-02-24 10:59:46.592946 [-] Traceback (most recent call last):
2017-02-24 10:59:46.593075 [-]   File "/app/slyd/bin/slyd", line 28, in <module>
2017-02-24 10:59:46.593175 [-]     splash.server.main(server_factory=make_server, argv=[])
2017-02-24 10:59:46.593235 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 372, in main
2017-02-24 10:59:46.593341 [-]     server_factory=server_factory,
2017-02-24 10:59:46.593395 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 291, in default_splash_server
2017-02-24 10:59:46.593485 [-]     argument_cache_max_entries=argument_cache_max_entries,
2017-02-24 10:59:46.593535 [-]   File "/app/slyd/bin/slyd", line 25, in make_server
2017-02-24 10:59:46.593596 [-]     'docroot': opts.root}))
2017-02-24 10:59:46.593644 [-]   File "/app/slyd/slyd/tap.py", line 88, in makeService
2017-02-24 10:59:46.593710 [-]     root = create_root(config, settings_module)
2017-02-24 10:59:46.593756 [-]   File "/app/slyd/slyd/tap.py", line 61, in create_root
2017-02-24 10:59:46.593815 [-]     for file_name in listdir(config['docroot']):
2017-02-24 10:59:46.593872 [-] OSError: [Errno 2] No such file or directory: '/app/portiaui/dist'
Performing system checks...

System check identified no issues (0 silenced).

You have 12 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, contenttypes, db_repo, sessions.
Run 'python manage.py migrate' to apply them.

February 24, 2017 - 10:59:47
Django version 1.10.1, using settings 'portia_server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

**Comment by ruairif** [comment]
You're missing the assets directory::

    docker run -i -t --rm -p 9001:9001 --name portia \
        -v $(pwd)/data:/app/slyd/data:rw \
        -v ~/portia/portia/portiaui/dist:/app/portiaui/dist \
        portia

**Comment by aleixsb** [comment]
ok thanks! Now it's starting but i'm getting 404 Not Found for http://localhost:9001/static/index.html

portiaui folder doesn't contain any dist folder so when I create the volume portiaui/dist:/app/portiaui/dist in docker it's empty and I suppose this is why I'm getting this error, is you path correct?

Also in the official documentation the docker command it's:
docker run -i -t --rm -v <PROJECT_FOLDER>/data:/app/slyd/data:rw -p 9001:9001 --name portia portia

That's why I wasn't mounting this volume, does it need an update?

Thanks for your help!

**Comment by ruairif** [comment]
The documentation is outdated. The most up to date instructions are [here](https://github.com/scrapinghub/portia/blob/develop/docs/installation.rst#developing-portia-using-docker)

**Comment by aleixsb** [comment]
thanks!
