### ISSUE TITLE
How to create new project using Docker version

### ISSUE THREAD

**Issue by Jacobh2** [scrapinghub/portia#736]
Running the provided docker image using the following command:
`docker run -it --rm -v ~/data:/app/data/projects:rw -p 9001:9001 scrapinghub/portia`

results in a portia container starting and I'm able to point my browser to `localhost:9001/` and the Portia spider appears.

But there is no button etc for creating a new project! I tried to manually create a folder in my `~/data` folder, and it appeared as a project when reloading the page. Is there any way a new project can be created directly from the page?

Also, I get this log:
```
[03/Mar/2017 15:21:35] "GET /server_capabilities HTTP/1.0" 500 15821
Internal Server Error: /server_capabilities
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/portia_server/portia_server/views.py", line 8, in capabilities
    'username': request.user.username,
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 234, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 380, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 180, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 207, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 35, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session```

**Comment by ruairif** [comment]
I can't recreate it. Can you try running docker pull again?

**Comment by Jacobh2** [comment]
Deleted the image and ran this again, got this:

```
$ docker run -it --rm -v ~/data:/app/data/projects:rw -p 9001:9001 scrapinghub/portia
Unable to find image 'scrapinghub/portia:latest' locally
latest: Pulling from scrapinghub/portia
c60055a51d74: Pull complete
755da0cdb7d2: Pull complete
969d017f67e6: Pull complete
37c9a9113595: Pull complete
a3d9f8479786: Pull complete
c950e8155cb9: Pull complete
eba39be7aaef: Pull complete
086f4ce28fd2: Pull complete
6fb4b8c14322: Pull complete
94d6b29d7c64: Pull complete
deb8acc6a07a: Pull complete
33d8ae0ebc35: Pull complete
de74bbe19625: Pull complete
d4ee32f6b2f8: Pull complete
Digest: sha256:1676498c8f014da05a88aeadfef7b6e546af1121755d151cc76c6a6d21696200
Status: Downloaded newer image for scrapinghub/portia:latest
+ action=
+ shift
+ '[' -z '' ']'
+ _run
+ service nginx start
+ _set_env
+ path=/app/portia_server:/app/slyd:/app/slybot
+ export PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ echo /app/portia_server:/app/slyd:/app/slybot
/app/portia_server:/app/slyd:/app/slybot
+ /app/portia_server/manage.py runserver
+ /app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist
2017-03-03 16:56:10+0000 [-] Log opened.
2017-03-03 16:56:10.582438 [-] Splash version: 2.3.1
2017-03-03 16:56:10.583155 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-03-03 16:56:10.583346 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-03-03 16:56:10.583427 [-] Python 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
2017-03-03 16:56:10.583695 [-] Open files limit: 1048576
2017-03-03 16:56:10.583874 [-] Can't bump open files limit
2017-03-03 16:56:10.823184 [-] Xvfb is started: ['Xvfb', ':1244231666', '-screen', '0', '1024x768x24']
2017-03-03 16:56:12.717321 [-] Site starting on 9002
2017-03-03 16:56:12.717835 [-] Starting factory <slyd.server.Site instance at 0x7f576c7c0170>
Performing system checks...

System check identified no issues (0 silenced).

You have 12 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, contenttypes, db_repo, sessions.
Run 'python manage.py migrate' to apply them.

March 03, 2017 - 16:56:14
Django version 1.10.5, using settings 'portia_server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /server_capabilities
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/portia_server/portia_server/views.py", line 8, in capabilities
    'username': request.user.username,
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 234, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 380, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 180, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 207, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 35, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
```

I'm on a mac pro running osx `10.12.3`

```
$ docker --version
Docker version 17.03.0-ce, build 60ccb22
$ docker-machine --version
docker-machine version 0.10.0, build 76ed2a6
```

I'll try this as well on a Win10 Pro to see if it works any better!

**Comment by ruairif** [comment]
I don't use kubernetes so I can't be sure why it isn't working. You could try disabling the django sessions plugin and it might work. You'll find more info [here](https://docs.djangoproject.com/en/1.8/topics/http/sessions/), the settings file is at `portia_server/portia_server/settings.py`

**Comment by hackrush01** [comment]
@Jacobh2 can you please follow the following steps and tell if the issue was resolved
1. run your server using the command `docker run -it --name portia --rm -v ~/data:/app/data/projects:rw -p 9001:9001 scrapinghub/portia`
2. execute the following in a new terminal window/tab `docker exec -it portia python /app/portia_server/manage.py migrate`
3. wait for the command to complete execution
4. close this terminal window and exit the docker server using `CTRL+C` in the previous terminal
5. re run the server using the command `docker run -it --rm -v ~/data:/app/data/projects:rw -p 9001:9001 scrapinghub/portia` and check if the problem was resolved.

**Comment by Jacobh2** [comment]
Thank you very much @hackrush01! Your steps seems to make it work! Both on my mac, as well as in my Kubernetes cluster 😃 

How come these steps are necessary when running the docker image in a non Windows environment?

**Comment by hackrush01** [comment]
Those steps are necessary to create tables, and other database related stuff, but I don't know how it worked on windows. I'll try it on windows and let you know if I could find anything.
