### ISSUE TITLE
How to install portia in Ubuntu 14.04

### ISSUE THREAD

**Issue by Mr-Phoebe** [scrapinghub/portia#742]
I follow the _[Documentation](http://portia.readthedocs.io/en/latest/installation.html#developing-portia-using-docker)_ , and choose to install Docker. And I can run Portia using  

`docker run -i -t --rm -v <PROJECTS_FOLDER>:/app/data/projects:rw -p 9001:9001 scrapinghub/portia`

 But I can use it to design a spider but can't run it and can't find the Log to solve the problem . Also I am sure that the spider is OK because I ever run a spider in Scrapinghub.  

And then I use _[Developing Portia using Docker](http://portia.readthedocs.io/en/latest/installation.html#developing-portia-using-docker)_ to build a Portia project but when it goes to 

`docker build . -t portia`

it shows
> root@ubuntu:/home/wuhaonan/portia/portiaui# ember build
Built project successfully. Stored in "dist/".
root@ubuntu:/home/wuhaonan/portia/portiaui# docker build . -t portia
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/wuhaonan/portia/portiaui/Dockerfile: no such file or directory

And I can't find any solution in Stackoverflow, so how can I deal with it?

**Comment by hackrush01** [comment]
Please follow the steps given at the bottom in #736 
This is for the docker approach, not using the develop using docker.

**Comment by Mr-Phoebe** [comment]
@hackrush01 Thank you for your help, but it doesn't work.

![image](https://cloud.githubusercontent.com/assets/15867761/23587540/85e14b42-01e9-11e7-9292-51ffb8284e96.png)

And the console shows

> Internal Server Error: /api/projects/test/spiders/blog.csdn.net/schedule
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/app/portia_server/portia_api/resources/route.py", line 74, in dispatch
    return super(JsonApiRoute, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/app/portia_server/portia_api/resources/route.py", line 77, in handle_exception
    response = super(JsonApiRoute, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/portia_server/portia_api/resources/spiders.py", line 82, in schedule
    request = requests.post(settings.SCHEDULE_URL, data=schedule_data)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /schedule.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff264517a90>: Failed to establish a new connection: [Errno 111] Connection refused',))
[05/Mar/2017 13:19:22] "POST /api/projects/test/spiders/blog.csdn.net/schedule HTTP/1.0" 500 14774

**Comment by hackrush01** [comment]
Can you please give more detail as to which site you are trying to scrape and the exact step you followed up until now. Because the error log shows that connection to the site was refused. Maybe then we can zero in on the problem.

**Comment by Mr-Phoebe** [comment]
@hackrush01 I scrape my blog's [article lists](http://blog.csdn.net/u013007900?viewmode=contents).

And this site is be accessable in portia, while I use 

`docker run -i -t --rm -v ~:/app/data/projects:rw -p 9001:9001 scrapinghub/portia`

to run it.

I can create a project, spiders and examples in `127.0.0.1:9001`. I can edit everything in the browser, but I can run the spider through it.

**Comment by Mr-Phoebe** [comment]
This is Portia, my spider and items.

![image](https://cloud.githubusercontent.com/assets/15867761/23587929/659dafea-01f0-11e7-9484-70fd14e8a975.png)

Is the possible reason that I try to scrape the site in China?

**Comment by hackrush01** [comment]
I think it's a more general problem, I too am not able to scrape websites designed in languages other that English(such as French, Hindi etc).

**Comment by Mr-Phoebe** [comment]
@hackrush01 But I can scrape the websites with Chinese characters in [Scrapinghub](https://portia.scrapinghub.com/). And the console shows that there are something wrong about the connection.

**Comment by ruairif** [comment]
@Mr-Phoebe For that to work you need to have [scrapyd](https://scrapyd.readthedocs.io/en/stable/) running so it can receive your spider and load it.

**Comment by Mr-Phoebe** [comment]
@ruairif Thank you for your help.

I installed scrapyd, but failed to run it.  It shows

`Failed to load application: 'module' object has no attribute 'OP_NO_TLSv1_1'`

So I try to update pyopenssl with the advice from [here](http://stackoverflow.com/questions/42450593/trying-to-use-twisted-on-osx), but I can't do it.

Does it need a virtual environment?

Or how to deal with it.

I appologize for my naive and poor behavior. But I really need help.

**Comment by ruairif** [comment]
You can install it in  a venv and install a more up to date openssl

**Comment by wenerme** [comment]
Same problem 

```
docker run --rm -it -v ~/data/portia:/app/data/projects:rw -p 9001:9001 scrapinghub/portia
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/app/portia_server/portia_api/resources/route.py", line 74, in dispatch
    return super(JsonApiRoute, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/app/portia_server/portia_api/resources/route.py", line 77, in handle_exception
    response = super(JsonApiRoute, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/portia_server/portia_api/resources/spiders.py", line 82, in schedule
    request = requests.post(settings.SCHEDULE_URL, data=schedule_data)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /schedule.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f577c3ec850>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by marrrcin** [comment]
The issue still occurs on both Ubuntu 16 and Windows 10 x64 when running using docker:
```
docker run -i -t --rm -v /home/marcin/portia:/app/data/projects:rw -p 9001:9001 scrapinghub/portia
```
