### ISSUE TITLE
Get UnicodeDecodeError when opening the portia

### ISSUE THREAD

**Issue by ZakiHe** [scrapinghub/portia#770]
I use docer to run portia and use the following commend to start it in docker:
docker run -i -t --rm -v ~:/app/data/projects:rw -p 9001:9001 scrapinghub/portia.
PS: I'm in the portia-master folder
Then I get the UnicodeDecodeError from django/core/files/storage.py

**Comment by ZakiHe** [comment]
2017-03-28 01:43:56.284993 [-] "127.0.0.1" - - [28/Mar/2017:01:43:55 +0000] "GET / HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
Internal Server Error: /api/projects
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/app/portia_server/portia_api/resources/route.py", line 74, in dispatch
    return super(JsonApiRoute, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/app/portia_server/portia_api/resources/route.py", line 77, in handle_exception
    response = super(JsonApiRoute, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/portia_server/portia_api/resources/route.py", line 223, in list
    collection = self.filter_collection(self.get_collection())
  File "/app/portia_server/portia_api/resources/projects.py", line 189, in get_collection
    for project_id, name in iteritems(self.projects))
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/app/portia_server/portia_api/resources/projects.py", line 55, in projects
    return storage_class.get_projects(self.request.user)
  File "/app/portia_server/storage/backends.py", line 72, in get_projects
    dirs, _ = cls('').listdir('')
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 400, in listdir
    if os.path.isdir(os.path.join(path, entry)):
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 1: ordinal not in range(128)
[28/Mar/2017 01:43:57] "GET /api/projects HTTP/1.0" 500 14361

**Comment by ruairif** [comment]
I have no programmatic solution for this at the moment but it will be fixed when we move to python 3. You can solve it by changing the path that you're reading projects from to only have ascii characters.
