### ISSUE TITLE
slybot new version's bug

### ISSUE THREAD

**Issue by AlexTanbz** [scrapinghub/portia#783]
I use portia2.0 to download spider as portia(by the way, download as scrapy is not worked, the error is  504 Gateway Time-out), and  use the portiacrawl to crawl the page. But something wrong:
`Unhandled error in Deferred:
CRITICAL:twisted:Unhandled error in Deferred:
2017-04-20 13:58:08 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 163, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 167, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 94, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiders/__init__.py", line 50, in from_crawler
    spider = cls(*args, **kwargs)
  File "/app/slybot/slybot/spidermanager.py", line 54, in __init__
    **kwargs)
  File "/app/slybot/slybot/spider.py", line 58, in __init__
    settings, spec, item_schemas, all_extractors)
  File "/app/slybot/slybot/spider.py", line 226, in _configure_plugins
    self.logger)
  File "/app/slybot/slybot/plugins/scrapely_annotations/annotations.py", line 89, in setup_bot
    self.extractors.append(SlybotIBLExtractor(list(group)))
  File "/app/slybot/slybot/plugins/scrapely_annotations/extraction/extractors.py", line 61, in __init__
    for p, v in zip(parsed_templates, template_versions)
  File "/app/slybot/slybot/plugins/scrapely_annotations/extraction/extractors.py", line 70, in build_extraction_tree
    basic_extractors = ContainerExtractor.apply(template, basic_extractors)
  File "/app/slybot/slybot/plugins/scrapely_annotations/extraction/container_extractors.py", line 65, in apply
    extraction_tree = cls._build_extraction_tree(containers)
  File "/app/slybot/slybot/plugins/scrapely_annotations/extraction/container_extractors.py", line 144, in _build_extraction_tree
    parent = containers[parent_id]
exceptions.KeyError: u'42f6-40bf-8154#parent'
CRITICAL:twisted:
2017-04-20 13:58:08 [twisted] CRITICAL: `

**Comment by ruairif** [comment]
The spider you are trying to download is broken which is why it fails to download or run using portiacrawl
