### ISSUE TITLE
ImportError: No module named portia_server.settings

### ISSUE THREAD

**Issue by RickChina** [scrapinghub/portia#792]
when I running slyd/bin/slyd -p 9002 -r portiaui/dist &
portia_server/manage.py runserver

2017-05-09 10:22:26.489985 [-] Splash version: 2.3.2
2017-05-09 10:22:26.493026 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-05-09 10:22:26.493196 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-05-09 10:22:26.493296 [-] Python 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
2017-05-09 10:22:26.493416 [-] Open files limit: 1024
2017-05-09 10:22:26.493510 [-] Open files limit increased from 1024 to 65536
2017-05-09 10:22:26.607155 [-] Xvfb is started: ['Xvfb', ':960888956', '-screen', '0', '1024x768x24', '-nolisten', 'tcp']
Xlib:  extension "RANDR" missing on display ":960888956".
2017-05-09 10:22:28.052836 [-] Traceback (most recent call last):
2017-05-09 10:22:28.061544 [-]   File "slyd/bin/slyd", line 28, in <module>
2017-05-09 10:22:28.061724 [-]     splash.server.main(server_factory=make_server, argv=[])
2017-05-09 10:22:28.061848 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 372, in main
2017-05-09 10:22:28.062011 [-]     server_factory=server_factory,
2017-05-09 10:22:28.062122 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 291, in default_splash_server
2017-05-09 10:22:28.062263 [-]     argument_cache_max_entries=argument_cache_max_entries,
2017-05-09 10:22:28.062396 [-]   File "slyd/bin/slyd", line 25, in make_server
2017-05-09 10:22:28.062509 [-]     'docroot': opts.root}))
2017-05-09 10:22:28.062615 [-]   File "/home/python/Desktop/test/portia/slyd/slyd/tap.py", line 88, in makeService
2017-05-09 10:22:28.062733 [-]     root = create_root(config, settings_module)
2017-05-09 10:22:28.062838 [-]   File "/home/python/Desktop/test/portia/slyd/slyd/tap.py", line 51, in create_root
2017-05-09 10:22:28.062949 [-]     configure_django(settings)
2017-05-09 10:22:28.063053 [-]   File "/home/python/Desktop/test/portia/slyd/slyd/tap.py", line 44, in configure_django
2017-05-09 10:22:28.063162 [-]     django.setup()
2017-05-09 10:22:28.063265 [-]   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 22, in setup
2017-05-09 10:22:28.063694 [-]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2017-05-09 10:22:28.063857 [-]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
2017-05-09 10:22:28.064484 [-]     self._setup(name)
2017-05-09 10:22:28.064725 [-]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
2017-05-09 10:22:28.064881 [-]     self._wrapped = Settings(settings_module)
2017-05-09 10:22:28.065002 [-]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
2017-05-09 10:22:28.065132 [-]     mod = importlib.import_module(self.SETTINGS_MODULE)
2017-05-09 10:22:28.065245 [-]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
2017-05-09 10:22:28.065813 [-]     __import__(name)
2017-05-09 10:22:28.065989 [-] ImportError: No module named portia_server.settings

**Comment by zhitie** [comment]
I have this problem, too

**Comment by justsomeguyinla** [comment]
Same problem here.  I followed the instructions for the standalone installation on a fresh install of Ubuntu 14.04.5.
