### ISSUE TITLE
error when install portia 2.0.8 on Ubuntu

### ISSUE THREAD

**Issue by brogs-php** [scrapinghub/portia#811]
Hello,

thi is my always-error when follow the principal instructions to install Portia 2.0.8 in Ubuntu 14.4. I googled more time searching a solutions but it's appears impossible to install last portia on Ubuntu, with no vagrant and not docker support emulation, I would like run portia in a linux box
 
Please someone could be help me as to do this goal.
Many thanks at all!! good life. 

----
make[1]: Leaving directory `/builds/PyQt-gpl-5.5.1/QtGui'
cd QtWidgets/ && ( test -e Makefile || /opt/qt55/bin/qmake /builds/PyQt-gpl-5.5.1/QtWidgets/QtWidgets.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory `/builds/PyQt-gpl-5.5.1/QtWidgets'
g++ -c -pipe -fno-exceptions -O2 -Wall -W -D_REENTRANT -fPIC -DSIP_PROTECTED_IS_PUBLIC -Dprotected=public -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/python2.7 -I/opt/qt55/include -I/opt/qt55/include/QtWidgets -I/opt/qt55/include/QtGui -I/opt/qt55/include/QtCore -I. -I/opt/qt55/mkspecs/linux-g++ -o sipQtWidgetspart0.o sipQtWidgetspart0.cpp
{standard input}: Assembler messages:
{standard input}:379552: Warning: end of file not at end of a line; newline inserted
{standard input}:379745: Error: unbalanced parenthesis in operand 1.
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[1]: *** [sipQtWidgetspart0.o] Error 4
make[1]: Leaving directory `/builds/PyQt-gpl-5.5.1/QtWidgets'
make: *** [sub-QtWidgets-make_first-ordered] Error 2
Command failed (exitcode: 2), exiting...

**Comment by ruairif** [comment]
How much ram do you have on the system that you're compiling on?

**Comment by brogs-php** [comment]
Hello @ruairif 

thanks for your quick response; i assigned 512MB of physical ram to y laptop. You think there is a ram problem during the compilation of Qt5 or PyQt? In your opinion, how much ram should i allocate to my pc?

many thanks sir

**Comment by brogs-php** [comment]
@ruairif I have increased the memory of my pc and have finally managed to compile the first step, the provision dependency. Now after running these command.


PYTHONPATH='/vagrant/portia_server:/vagrant/slyd:/vagrant/slybot'
slyd/bin/slyd -p 9002 -r portiaui/dist & portia_server/manage.py runserver i get this multiple failure:

Traceback (most recent call last):
  File "slyd/bin/slyd", line 3, in <module>
    import splash.server
ImportError: No module named splash.server
Unhandled exception in thread started by <function wrapper at 0x7fed24c10cf8>
Traceback (most recent call last):
  File "/root/.virtualenvs/portia2/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/root/.virtualenvs/portia2/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/root/.virtualenvs/portia2/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/root/.virtualenvs/portia2/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/root/.virtualenvs/portia2/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.virtualenvs/portia2/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/root/.virtualenvs/portia2/local/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whitenoise

many thanks sir

**Comment by ruairif** [comment]
did you `pip install` the `requirements.txt` files in the `slybot` and `portia_server` directories?

**Comment by brogs-php** [comment]
Hello @ruairif,  The portia documentation does not mention this two update.. However i ran the two requirements.txt, then run again slyd/bin/slyd -p 9002 -r portiaui/dist & port_server/manage.py runserver. The first traceback i see:

Traceback (most recent call last):
  File "slyd/bin/slyd", line 3, in <module>
    import splash.server
ImportError: No module named splash.server
Performing system checks...

Then the setup proceeds and ends with this spool:

You have 12 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, contenttypes, db_repo, sessions.
Run 'python manage.py migrate' to apply them.

July 20, 2017 - 10:15:29
Django version 1.10.5, using settings 'portia_server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

If all it's correct, to which address there is a connection for portia, :9001 or :8000?
It loses my inability to install this project!

many thanks sir

**Comment by brogs-php** [comment]
Hello @ruairif  can you help me again a shot.. 

many thanks

**Comment by RickChina** [comment]
Hi, I have a similar problem, may I ask your problem solved?

**Comment by brogs-php** [comment]
hello @RickChina 

not sorry,  support leave me alone.
