### ISSUE TITLE
No such file or directory: 'portiaui/dist',when I install on ubuntu14.04

### ISSUE THREAD

**Issue by RickChina** [scrapinghub/portia#819]
I want to install portia on my Ubuntu14.04 , but when I running portia useing
 "**slyd/bin/slyd -p 9002 -r portiaui/dist & portia_server/manage.py runserver"**,
 an error occurred：
python@ubuntu:~/Desktop/portia2/portia$ slyd/bin/slyd -p 9002 -r portiaui/dist & portia_server/manage.py runserver
[1] 9551
2017-09-18 00:49:18-0700 [-] Log opened.
2017-09-18 00:49:18.969082 [-] Splash version: 2.3.3
2017-09-18 00:49:18.974024 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2017-09-18 00:49:18.974326 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1
2017-09-18 00:49:18.974499 [-] Python 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
2017-09-18 00:49:18.974722 [-] Open files limit: 1024
2017-09-18 00:49:18.974897 [-] Open files limit increased from 1024 to 4096
2017-09-18 00:49:19.101627 [-] Xvfb is started: ['Xvfb', ':2018149789', '-screen', '0', '1024x768x24', '-nolisten', 'tcp']
Xlib:  extension "RANDR" missing on display ":2018149789".
2017-09-18 07:49:23.665381 [-] Traceback (most recent call last):
2017-09-18 07:49:23.665716 [-]   File "slyd/bin/slyd", line 34, in <module>
2017-09-18 07:49:23.665914 [-]     splash.server.main(server_factory=make_server, argv=[])
2017-09-18 07:49:23.666068 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 372, in main
2017-09-18 07:49:23.666290 [-]     server_factory=server_factory,
2017-09-18 07:49:23.666435 [-]   File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 291, in default_splash_server
2017-09-18 07:49:23.666615 [-]     argument_cache_max_entries=argument_cache_max_entries,
2017-09-18 07:49:23.666779 [-]   File "slyd/bin/slyd", line 31, in make_server
2017-09-18 07:49:23.666925 [-]     'docroot': opts.root}))
2017-09-18 07:49:23.667058 [-]   File "/home/python/Desktop/portia2/portia/slyd/slyd/tap.py", line 88, in makeService
2017-09-18 07:49:23.667266 [-]     root = create_root(config, settings_module)
2017-09-18 07:49:23.667467 [-]   File "/home/python/Desktop/portia2/portia/slyd/slyd/tap.py", line 61, in create_root
2017-09-18 07:49:23.667698 [-]     for file_name in listdir(config['docroot']):
2017-09-18 07:49:23.667901 [-] OSError: [Errno 2] No such file or directory: 'portiaui/dist'
Performing system checks...

System check identified no issues (0 silenced).

You have 12 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, contenttypes, db_repo, sessions.
Run 'python manage.py migrate' to apply them.

September 18, 2017 - 07:49:26
Django version 1.10.5, using settings 'portia_server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

How can I deal with it?

**Comment by SimeonZhang** [comment]
try this:

1. install [Node.js](https://nodejs.org/en/download/package-manager/), [Bower](https://bower.io/#install-bower), and [ember-cli](https://ember-cli.com/).

2. run this command below

- cd portia/portiaui
- npm install && bower install
- cd node_modules/ember-cli && npm install && cd ../../
- ember build

**Comment by RickChina** [comment]
@SimeonZhang Thank you very much, I solved the problem！
