### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 92036: invalid start byte

### ISSUE THREAD

**Issue by vishaln79** [scrapinghub/portia#881]
Hello,

I am running the dockerized portiacrawl and keep running into this UnicodeDecodeError. I saw this issue reported previously as well, with a fix expected when portia was ported over to python 3. Could you kindly explain what the issue is specifically, is there some way I could get around it and is a fix expected soon?

Thanks a lot!
Vishal.

**Comment by vishaln79** [comment]
Wanted to provide the trace for this error. I tried running portiacrawl locally:

Traceback (most recent call last):
  File "/apps/portia/slybot/slybot/utils.py", line 368, in load_spider
    spec.setdefault("templates", []).extend(templates)
  File "/apps/portia/slybot/slybot/utils.py", line 408, in load_external_templates
    html = self.storage.open(sample_dir, fname, raw=1)
  File "/apps/portia/slybot/slybot/utils.py", line 326, in open
    return decode(f.read()) if raw else json.load(f)
  File "/apps/anaconda3/envs/py3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 92036: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/anaconda3/envs/py3/bin/scrapy", line 10, in <module>
    sys.exit(execute())
  File "/apps/anaconda3/envs/py3/lib/python3.6/site-packages/scrapy/cmdline.py", line 150, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/apps/anaconda3/envs/py3/lib/python3.6/site-packages/scrapy/cmdline.py", line 90, in _run_print_help
    func(*a, **kw)
  File "/apps/anaconda3/envs/py3/lib/python3.6/site-packages/scrapy/cmdline.py", line 157, in _run_command
    cmd.run(args, opts)
  File "/apps/anaconda3/envs/py3/lib/python3.6/site-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/apps/anaconda3/envs/py3/lib/python3.6/site-packages/scrapy/crawler.py", line 170, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/apps/anaconda3/envs/py3/lib/python3.6/site-packages/scrapy/crawler.py", line 198, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/apps/anaconda3/envs/py3/lib/python3.6/site-packages/scrapy/crawler.py", line 202, in _create_crawler
    spidercls = self.spider_loader.load(spidercls)
  File "/apps/portia/slybot/slybot/spidermanager.py", line 54, in load
    spec = self._specs["spiders"][spider_name]
  File "/apps/portia/slybot/slybot/utils.py", line 350, in __getitem__
    self._spiders[key] = self.load_spider(key)
  File "/apps/portia/slybot/slybot/utils.py", line 373, in load_spider
    (spider_name, e)
ValueError: Error parsing spider (invalid JSON): www.xxxx.com: 'utf-8' codec can't decode byte 0xa9 in position 92036: invalid start byte

**Comment by grrothman** [comment]
+1

**Comment by rachidio** [comment]
+1

**Comment by marcometz** [comment]
I think the problem is here in file

utils.py:327
`open(self._path(*args), encoding='utf-8')`

Encoding here is fixed to UTF-8 but can be anything else, depending on encoding of parsed html
