### ISSUE TITLE
UnicodeDecodeError： ‘utf-8’ codec can't decode byte 0xbf in position 289: invalid start byte

### ISSUE THREAD

**Issue by innopure** [scrapinghub/portia#882]
This error occurred while running **https://bbs.360che.com/**. I don't know why. I hope someone who is strong can solve it.

**Comment by innopure** [comment]
[18/Mar/2019 07:29:27] "PATCH /api/projects/yiqi/spiders/bbs.360che.com/samples/5b7e-4ac3-9e86 HTTP/1.0" 500 17950
Internal Server Error: /api/projects/yiqi/spiders/bbs.360che.com/samples/5b7e-4ac3-9e86
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/utils.py", line 319, in _get_value_for_key
    return obj[key]
TypeError: 'Sample' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/portia_server/portia_orm/relationships.py", line 98, in __get__
    assert field is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/viewsets.py", line 95, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/app/portia_server/portia_api/resources/route.py", line 72, in dispatch
    return super(JsonApiRoute, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/app/portia_server/portia_api/resources/route.py", line 75, in handle_exception
    response = super(JsonApiRoute, self).handle_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/portia_server/portia_api/resources/route.py", line 239, in retrieve
    return Response(serializer.data, status=HTTP_200_OK)
  File "/app/portia_server/portia_api/jsonapi/serializers.py", line 213, in data
    return self.dump(self.instance).data
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 496, in dump
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 146, in serialize
    index=(index if index_errors else None)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 67, in call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 140, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/fields.py", line 241, in serialize
    value = self.get_value(attr, obj, accessor=accessor)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/fields.py", line 185, in get_value
    return accessor_func(check_key, obj, default)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 404, in get_attribute
    return utils.get_value(attr, obj, default)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/utils.py", line 306, in get_value
    return _get_value_for_keys(key.split('.'), obj, default)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/utils.py", line 311, in _get_value_for_keys
    return _get_value_for_key(keys[0], obj, default)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/utils.py", line 322, in _get_value_for_key
    attr = getattr(obj, key)
  File "/app/portia_server/portia_orm/relationships.py", line 101, in __get__
    self.related_name: instance
  File "/app/portia_server/portia_orm/models.py", line 890, in load
    storage, instance, sample=sample, **kwargs)
  File "/app/portia_server/portia_orm/base.py", line 589, in load
    file_data, many=many).data
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 544, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/app/portia_server/portia_orm/serializers.py", line 85, in _do_load
    data, many, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 612, in _do_load
    index_errors=self.opts.index_errors,
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 294, in deserialize
    index=(index if index_errors else None)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 67, in call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 287, in <lambda>
    data
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/fields.py", line 263, in deserialize
    output = self._deserialize(value, attr, data)
    index=(index if index_errors else None)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 67, in call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 140, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/fields.py", line 241, in serialize
    value = self.get_value(attr, obj, accessor=accessor)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/fields.py", line 185, in get_value
    return accessor_func(check_key, obj, default)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 404, in get_attribute
    return utils.get_value(attr, obj, default)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/utils.py", line 306, in get_value
    return _get_value_for_keys(key.split('.'), obj, default)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/utils.py", line 311, in _get_value_for_keys
    return _get_value_for_key(keys[0], obj, default)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/utils.py", line 322, in _get_value_for_key
    attr = getattr(obj, key)
  File "/app/portia_server/portia_orm/relationships.py", line 101, in __get__
    self.related_name: instance
  File "/app/portia_server/portia_orm/models.py", line 890, in load
    storage, instance, sample=sample, **kwargs)
  File "/app/portia_server/portia_orm/base.py", line 589, in load
    file_data, many=many).data
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 544, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/app/portia_server/portia_orm/serializers.py", line 85, in _do_load
    data, many, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 612, in _do_load
    index_errors=self.opts.index_errors,
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 294, in deserialize
    index=(index if index_errors else None)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 67, in call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 287, in <lambda>
    data
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/fields.py", line 263, in deserialize
    output = self._deserialize(value, attr, data)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/fields.py", line 575, in _deserialize
    return utils.ensure_text_type(value)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/utils.py", line 286, in ensure_text_type
    val = val.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 289: invalid start byte

**Comment by innopure** [comment]
Oh, he made three mistakes. I don't know the main reason.
