### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by lerinoi** [scrapinghub/portia#891]
Hi, installed locally, run through docker
docker run -i -t --rm -p 9001:9001 \
    -v /Users/yleemini/Documents/projects/q/new/portia:/app/data/projects:rw \
    -v ~/Documents/projects/portia/portiaui/dist:/app/portiaui/dist \
    -v ~/Documents/projects/portia/slyd:/app/slyd \
    -v ~/Documents/projects/portia/portia_server:/app/portia_server \
    portia
Trying to open
https://online-kassa.ru/kupit/cat/kassy/

I get an application error:
Traceback (most recent call last):
  File "/app/slyd/slyd/splash/ferry.py", line 220, in wrapUrl
    return wrap_url(text(url), self.protocol.user.tabid, text(baseuri))
  File "/app/slyd/slyd/splash/css_utils.py", line 17, in wrap_url
    url = urljoin_rfc(base, url)
  File "/usr/local/lib/python3.5/dist-packages/w3lib/url.py", line 609, in urljoin_rfc
    return urljoin(str_base, str_ref)
  File "/usr/lib/python3.5/urllib/parse.py", line 415, in urljoin
    base, url, _coerce_result = _coerce_args(base, url)
  File "/usr/lib/python3.5/urllib/parse.py", line 114, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/lib/python3.5/urllib/parse.py", line 98, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/lib/python3.5/urllib/parse.py", line 98, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

**Comment by Robinsir** [comment]
i have same promble.

**Comment by CarlosBalladares** [comment]
Is this related to support for SPA? 
Mine seems to crash only for SPA web apps like something bootstraped with vue cli or cra

**Comment by Rainmaker33** [comment]
I have the same problem
