### ISSUE TITLE
Blank white page on localhost and portia says: PermisionDenied

### ISSUE THREAD

**Issue by svblsvljb** [scrapinghub/portia#915]
After i am starting portia vie docker:
```
docker run -i -t --rm -v $DOCKER_VOLUMES/portia/aw:/app/data/projects:rw -p 9001:9001 scrapinghub/portia
+ action=
+ shift
+ '[' -z '' ']'
+ _run
+ service nginx start
+ _set_env
+ path=/app/portia_server:/app/slyd:/app/slybot
+ export PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ PYTHONPATH=/app/portia_server:/app/slyd:/app/slybot
+ echo /app/portia_server:/app/slyd:/app/slybot
/app/portia_server:/app/slyd:/app/slybot
+ /app/portia_server/manage.py runserver
+ /app/slyd/bin/slyd -p 9002 -r /app/portiaui/dist
Watching for file changes with StatReloader
Performing system checks...

2021-05-19 13:37:33+0000 [-] Log opened.
2021-05-19 13:37:34.505102 [-] Splash version: 3.2
2021-05-19 13:37:34.505843 [-] Qt 5.9.1, PyQt 5.9, WebKit 602.1, sip 4.19.3, Twisted 19.2.1, Lua 5.2
2021-05-19 13:37:34.506006 [-] Python 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
2021-05-19 13:37:34.506215 [-] Open files limit: 1024
2021-05-19 13:37:34.506360 [-] Can't bump open files limit
2021-05-19 13:37:34.897038 [-] Xvfb is started: ['Xvfb', ':1467546407', '-screen', '0', '1024x768x24', '-nolisten', 'tcp']
System check identified no issues (0 silenced).
May 19, 2021 - 13:37:40
Django version 2.2.3, using settings 'portia_server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
2021-05-19 13:37:44.000615 [-] Site starting on 9002
2021-05-19 13:37:44.000722 [-] Starting factory <slyd.server.Site object at 0x7f177fe791d0>
2021-05-19 13:38:37.657044 [-] "127.0.0.1" - - [19/May/2021:13:38:37 +0000] "GET / HTTP/1.0" 200 2021 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
2021-05-19 13:38:39.001738 [-] "127.0.0.1" - - [19/May/2021:13:38:38 +0000] "GET /favicon.ico HTTP/1.0" 404 153 "http://localhost:9001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
Internal Server Error: /api/projects
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/viewsets.py", line 95, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/app/portia_server/portia_api/resources/route.py", line 72, in dispatch
    return super(JsonApiRoute, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/app/portia_server/portia_api/resources/route.py", line 75, in handle_exception
    response = super(JsonApiRoute, self).handle_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/portia_server/portia_api/resources/route.py", line 223, in list
    collection = self.filter_collection(self.get_collection())
  File "/app/portia_server/portia_api/resources/projects.py", line 234, in get_collection
    for project_id, name in iteritems(self.projects))
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/app/portia_server/portia_api/resources/projects.py", line 76, in projects
    return storage_class.get_projects(self.request.user)
  File "/app/portia_server/storage/backends.py", line 76, in get_projects
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 686, in reraise
    raise value
  File "/app/portia_server/storage/backends.py", line 72, in get_projects
    dirs, _ = cls('').listdir('')
  File "/usr/local/lib/python3.5/dist-packages/django/core/files/storage.py", line 315, in listdir
    for entry in os.scandir(path):
PermissionError: [Errno 13] Permission denied: '/app/data/projects'
[19/May/2021 13:38:39] "GET /api/projects HTTP/1.0" 500 15011
````

 Output folder are okay.
 
OS: fedora33 - linux-rpm-based
RAM and CPU are OK

**Comment by praveenaki** [comment]
Seems like the project is no longer supported. Last commit is 2019 and the official news confirming the same here - https://www.zyte.com/blog/announcing-portia saying - "Note: Portia is no longer available for new users. It has been disabled for all the new organisations from August 20, 2018 onward."
