### ISSUE TITLE
slybot jsonschema validation is broken with jsonschema >= 2.0.0

### ISSUE THREAD

**Issue by kmike** [scrapinghub/portia#92]
jsonschema >= 2.0.0 changed the way Draft3Validator is created, so this method: https://github.com/scrapinghub/portia/blob/7ab8dd990b946e92a928a6692ecd4706e60b5930/slybot/slybot/validation/schema.py#L21 does nothing. 

Tests are failing for slybot:

```
======================================================================
FAIL: test_invalid_url (test_schema_validation.JsonSchemaTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kmike/svn/slybot/slybot/tests/test_schema_validation.py", line 66, in test_invalid_url
    self.assertRaisesRegexp(ValidationError, "Invalid url:", validator.validate, obj)
  File "/Users/kmike/svn/slybot/slybot/tests/test_schema_validation.py", line 23, in assertRaisesRegexp
    raise AssertionError("%s not raised" % eclass.__name__)
AssertionError: ValidationError not raised

======================================================================
FAIL: test_regex_formatting_wrong (test_schema_validation.JsonSchemaTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kmike/svn/slybot/slybot/tests/test_schema_validation.py", line 35, in test_regex_formatting_wrong
    validator.validate, obj)
  File "/Users/kmike/svn/slybot/slybot/tests/test_schema_validation.py", line 23, in assertRaisesRegexp
    raise AssertionError("%s not raised" % eclass.__name__)
AssertionError: ValidationError not raised

----------------------------------------------------------------------
```

**Comment by ruairif** [comment]
The tests need to be updated but this issue has been resolved.
